# -*- coding: utf-8 -*-
"""
Impuls Longevity — contenido del sitio en 3 idiomas (ES / RU / EN).
Una sola fuente de verdad; build.py genera el HTML a partir de aquí.
No duplicar textos en las plantillas: todo el texto vive en este archivo.
"""

LANGS = ["es", "ca", "ru", "en"]

# --- Bases de URL por idioma (clean URLs con carpetas) ---
HOME = {"es": "/", "ca": "/ca/", "ru": "/ru/", "en": "/en/"}

# ------------------------------------------------------------------
# Iconos SVG por slug de servicio (trazo, heredan color)
# ------------------------------------------------------------------
ICONS = {
    "eliminacion-de-tatuajes": '<path d="M4 20l7-7m0 0l3-3 4 4-3 3m-4-4l4 4M14 4l6 6"/>',
    "rejuvenecimiento-cutaneo": '<path d="M12 3v2m0 14v2m9-9h-2M5 12H3m14.5-6.5l-1.4 1.4M7.9 16.1l-1.4 1.4m0-11.4l1.4 1.4m8.2 8.2l1.4 1.4"/><circle cx="12" cy="12" r="4"/>',
    "eliminacion-de-pigmentacion": '<circle cx="12" cy="12" r="8"/><circle cx="9" cy="10" r="1.3" fill="currentColor"/><circle cx="14" cy="14" r="1.3" fill="currentColor"/>',
    "depilacion-laser": '<path d="M12 2c1 3 1 5 0 8m4-6c.5 3 .5 5-1 7M8 4c-.5 3-.5 5 1 7M12 22a4 4 0 004-4H8a4 4 0 004 4z"/>',
    "tratamiento-del-acne": '<circle cx="12" cy="12" r="9"/><circle cx="9" cy="9" r="1.2" fill="currentColor"/><circle cx="15" cy="11" r="1.2" fill="currentColor"/><circle cx="11" cy="15" r="1.2" fill="currentColor"/>',
    "aranas-vasculares-rosacea": '<path d="M5 12s3-6 7-6 7 6 7 6-3 6-7 6-7-6-7-6z"/><path d="M9 9l6 6M15 9l-6 6"/>',
    "cicatrices-y-estrias": '<path d="M4 16c4-1 5-9 9-9s5 8 7 5"/><path d="M4 20c4-1 6-6 9-6"/>',
    "onicomicosis": '<path d="M8 20V8a4 4 0 018 0v12M8 14h8"/>',
    "rejuvenecimiento-4d-fotona": '<path d="M12 3l2.5 5 5.5.8-4 3.9.9 5.5L12 21l-4.9 2.2.9-5.5-4-3.9 5.5-.8z"/>',
    "eliminacion-de-neoplasias": '<path d="M12 3l7 3v5c0 4-3 7-7 9-4-2-7-5-7-9V6z"/><path d="M9.5 12l1.8 1.8L15 10"/>',
    "smas-lifting": '<path d="M12 21c-4-2-7-5-7-9a7 7 0 0114 0c0 4-3 7-7 9z"/><path d="M9 11l3-3 3 3"/>',
    "fotona-4glow": '<path d="M12 3l1.8 4.2L18 9l-4.2 1.8L12 15l-1.8-4.2L6 9z"/><circle cx="18" cy="17" r="1.2" fill="currentColor"/><circle cx="6.5" cy="17.5" r="1" fill="currentColor"/>',
    "control-de-peso": '<circle cx="12" cy="12" r="9"/><path d="M12 7.5v9m0 0l-3.2-3.2M12 16.5l3.2-3.2"/>',
    "salud-de-la-mujer": '<circle cx="12" cy="8" r="5"/><path d="M12 13v8M9 18h6"/>',
    "salud-del-hombre": '<circle cx="10" cy="14" r="5"/><path d="M14.5 9.5L20 4m0 0h-4.5M20 4v4.5"/>',
}

# ------------------------------------------------------------------
# Cadenas de interfaz comunes por idioma
# ------------------------------------------------------------------
UI = {
    "es": {
        "html_lang": "es",
        "menu": {"servicios": "Servicios", "programas": "Programas", "sobre": "Sobre nosotros", "tecnologia": "Tecnología", "preguntas": "Preguntas", "contacto": "Contacto"},
        "cta_nav": "Pide tu cita",
        "seo_h1_geo": " en Barcelona",
        "seo_title_suffix": "con láser en Barcelona",
        "seo_desc_suffix": "Clínica de estética láser en Barcelona. Pide tu cita en Impuls Longevity.",
        "back_home": "Inicio",
        "all_services": "Todos los servicios",
        "how_title": "Cómo funciona",
        "benefits_title": "Beneficios",
        "tech_used_title": "Tecnología que utilizamos",
        "faq_title": "Preguntas frecuentes",
        "service_cta_h": "Reserva tu valoración",
        "service_cta_p": "Cuéntanos tu caso y nuestro equipo diseñará un protocolo personalizado para ti.",
        "form": {"nombre": "Nombre", "telefono": "Teléfono", "email": "Email (opcional)", "mensaje": "¿Qué tratamiento te interesa?", "enviar": "Enviar solicitud", "privacidad": "Al enviar aceptas la política de privacidad.", "consent": "He leído y acepto la <a href='{url}'>política de privacidad</a>.", "success": "¡Gracias! Hemos recibido tu solicitud. Te contactaremos muy pronto.", "req": "Campos obligatorios"},
        "skip": "Saltar al contenido",
        "cookie_text": "Usamos cookies propias y de terceros para analizar el uso del sitio y mejorar tu experiencia. Puedes aceptarlas o rechazarlas.",
        "cookie_accept": "Aceptar", "cookie_reject": "Rechazar", "cookie_more": "Más información",
        "footer_tagline": "Impuls Longevity — clínica de estética láser avanzada en el centro de Barcelona. Tecnología Fotona, resultados seguros y naturales.",
        "footer_services": "Servicios",
        "footer_clinic": "Clínica",
        "footer_contact": "Contacto",
        "footer_about": "Sobre nosotros",
        "footer_blog": "Blog",
        "legal_note": "MALITA LASER S.L. (Impuls Longevity) · CIF B-01650035 · Plaza Urquinaona 6, 08010 Barcelona. Los tratamientos láser son actos sanitarios y sus resultados pueden variar según cada persona tras una valoración individualizada.",
        "copyright": "© 2020–2026 Impuls Longevity",
        "legal_links": [("Aviso legal", "aviso-legal"), ("Privacidad", "politica-de-privacidad"), ("Cookies", "politica-de-cookies")],
    },
    "ca": {
        "html_lang": "ca",
        "menu": {"servicios": "Serveis", "programas": "Programes", "sobre": "Sobre nosaltres", "tecnologia": "Tecnologia", "preguntas": "Preguntes", "contacto": "Contacte"},
        "cta_nav": "Demana cita",
        "seo_h1_geo": " a Barcelona",
        "seo_title_suffix": "amb làser a Barcelona",
        "seo_desc_suffix": "Clínica d'estètica làser a Barcelona. Demana cita a Impuls Longevity.",
        "back_home": "Inici",
        "all_services": "Tots els serveis",
        "how_title": "Com funciona",
        "benefits_title": "Beneficis",
        "tech_used_title": "Tecnologia que utilitzem",
        "faq_title": "Preguntes freqüents",
        "service_cta_h": "Reserva la teva valoració",
        "service_cta_p": "Explica'ns el teu cas i el nostre equip dissenyarà un protocol personalitzat per a tu.",
        "form": {"nombre": "Nom", "telefono": "Telèfon", "email": "Email (opcional)", "mensaje": "Quin tractament t'interessa?", "enviar": "Envia la sol·licitud", "privacidad": "En enviar acceptes la política de privacitat.", "consent": "He llegit i accepto la <a href='{url}'>política de privacitat</a>.", "success": "Gràcies! Hem rebut la teva sol·licitud. Et contactarem molt aviat.", "req": "Camps obligatoris"},
        "skip": "Vés al contingut",
        "cookie_text": "Utilitzem cookies pròpies i de tercers per analitzar l'ús del lloc i millorar la teva experiència. Pots acceptar-les o rebutjar-les.",
        "cookie_accept": "Accepta", "cookie_reject": "Rebutja", "cookie_more": "Més informació",
        "footer_tagline": "Impuls Longevity — clínica d'estètica làser avançada al centre de Barcelona. Tecnologia Fotona, resultats segurs i naturals.",
        "footer_services": "Serveis",
        "footer_clinic": "Clínica",
        "footer_contact": "Contacte",
        "footer_about": "Sobre nosaltres",
        "footer_blog": "Blog",
        "legal_note": "MALITA LASER S.L. (Impuls Longevity) · CIF B-01650035 · Plaza Urquinaona 6, 08010 Barcelona. Els tractaments amb làser són actes sanitaris i els seus resultats poden variar segons cada persona després d'una valoració individualitzada.",
        "copyright": "© 2020–2026 Impuls Longevity",
        "legal_links": [("Avís legal", "aviso-legal"), ("Privacitat", "politica-de-privacidad"), ("Cookies", "politica-de-cookies")],
    },
    "ru": {
        "html_lang": "ru",
        "menu": {"servicios": "Услуги", "programas": "Программы", "sobre": "О нас", "tecnologia": "Технологии", "preguntas": "Вопросы", "contacto": "Контакты"},
        "cta_nav": "Записаться",
        "seo_h1_geo": " в Барселоне",
        "seo_title_suffix": "лазером в Барселоне",
        "seo_desc_suffix": "Клиника лазерной эстетики в Барселоне. Запишитесь в Impuls Longevity.",
        "back_home": "Главная",
        "all_services": "Все услуги",
        "how_title": "Как это работает",
        "benefits_title": "Преимущества",
        "tech_used_title": "Используемые технологии",
        "faq_title": "Частые вопросы",
        "service_cta_h": "Запишитесь на консультацию",
        "service_cta_p": "Расскажите о своём случае — команда подберёт для вас индивидуальный протокол.",
        "form": {"nombre": "Имя", "telefono": "Телефон", "email": "Email (по желанию)", "mensaje": "Какая процедура вас интересует?", "enviar": "Отправить заявку", "privacidad": "Отправляя форму, вы принимаете политику конфиденциальности.", "consent": "Я прочитал(а) и принимаю <a href='{url}'>политику конфиденциальности</a>.", "success": "Спасибо! Мы получили вашу заявку и скоро свяжемся с вами.", "req": "Обязательные поля"},
        "skip": "Перейти к содержимому",
        "cookie_text": "Мы используем свои и сторонние cookies для анализа использования сайта и улучшения опыта. Вы можете принять или отклонить их.",
        "cookie_accept": "Принять", "cookie_reject": "Отклонить", "cookie_more": "Подробнее",
        "footer_tagline": "Impuls Longevity — клиника лазерной эстетики в центре Барселоны. Технология Fotona, безопасный и естественный результат.",
        "footer_services": "Услуги",
        "footer_clinic": "Клиника",
        "footer_contact": "Контакты",
        "footer_about": "О нас",
        "footer_blog": "Блог",
        "legal_note": "MALITA LASER S.L. (Impuls Longevity) · CIF B-01650035 · Plaza Urquinaona 6, 08010 Barcelona. Лазерные процедуры являются медицинскими; результат индивидуален и определяется после очной консультации.",
        "copyright": "© 2020–2026 Impuls Longevity",
        "legal_links": [("Правовая информация", "aviso-legal"), ("Конфиденциальность", "politica-de-privacidad"), ("Cookies", "politica-de-cookies")],
    },
    "en": {
        "html_lang": "en",
        "menu": {"servicios": "Services", "programas": "Programs", "sobre": "About us", "tecnologia": "Technology", "preguntas": "FAQ", "contacto": "Contact"},
        "cta_nav": "Book now",
        "seo_h1_geo": " in Barcelona",
        "seo_title_suffix": "with laser in Barcelona",
        "seo_desc_suffix": "Laser aesthetics clinic in Barcelona. Book your appointment at Impuls Longevity.",
        "back_home": "Home",
        "all_services": "All services",
        "how_title": "How it works",
        "benefits_title": "Benefits",
        "tech_used_title": "Technology we use",
        "faq_title": "Frequently asked questions",
        "service_cta_h": "Book your assessment",
        "service_cta_p": "Tell us about your case and our team will design a personalised protocol for you.",
        "form": {"nombre": "Name", "telefono": "Phone", "email": "Email (optional)", "mensaje": "Which treatment are you interested in?", "enviar": "Send request", "privacidad": "By submitting you accept the privacy policy.", "consent": "I have read and accept the <a href='{url}'>privacy policy</a>.", "success": "Thank you! We've received your request and will contact you soon.", "req": "Required fields"},
        "skip": "Skip to content",
        "cookie_text": "We use our own and third-party cookies to analyse site usage and improve your experience. You can accept or reject them.",
        "cookie_accept": "Accept", "cookie_reject": "Reject", "cookie_more": "More information",
        "footer_tagline": "Impuls Longevity — advanced laser aesthetics clinic in central Barcelona. Fotona technology, safe and natural results.",
        "footer_services": "Services",
        "footer_clinic": "Clinic",
        "footer_contact": "Contact",
        "footer_about": "About us",
        "footer_blog": "Blog",
        "legal_note": "MALITA LASER S.L. (Impuls Longevity) · CIF B-01650035 · Plaza Urquinaona 6, 08010 Barcelona. Laser treatments are medical procedures; results vary by individual following a personal assessment.",
        "copyright": "© 2020–2026 Impuls Longevity",
        "legal_links": [("Legal notice", "aviso-legal"), ("Privacy", "politica-de-privacidad"), ("Cookies", "politica-de-cookies")],
    },
}

# Datos de la empresa (del aviso legal original)
COMPANY = {
    "razon_social": "MALITA LASER S.L.",
    "comercial": "Impuls Longevity — Centro de Estética Impuls",
    "cif": "B-01650035",
    "direccion": "Plaza Urquinaona 6, Planta 14, Puerta A1, 08010 Barcelona",
    "email": "impuls.espana@gmail.com",
    "telefono": "+34 747 749 256",
    "registro_sanitario": "[U.48 pendiente]",
}

# Contacto (común, no se traduce salvo etiquetas)
CONTACT = {
    "address_html": "Pl. d'Urquinaona, 6, Piso 14, A1<br>08010 Barcelona",
    "phones": ["+34 747 749 256", "+34 66 22 66 999"],
    "phones_tel": ["+34747749256", "+34662266999"],
    "whatsapp": "34747749256",
    "instagram": "https://instagram.com/impuls_longevity",
    "facebook": "https://facebook.com/impuls.bcn",
}

# Marcas / tecnologías (tira de confianza)
BRANDS = ["Fotona StarWalker", "SP Dynamis", "Q-Switched", "Er:YAG · Nd:YAG", "Láser Fraccional"]

# ------------------------------------------------------------------
# HOME — contenido por idioma
# ------------------------------------------------------------------
HOME_CONTENT = {
    "es": {
        "title": "Impuls Longevity · Estética láser avanzada Fotona · Barcelona",
        "description": "Impuls Longevity — clínica de estética láser en Barcelona. Tecnología Fotona StarWalker y SP Dynamis: aclaración de tatuajes, depilación, rejuvenecimiento, acné y manchas. Más de 15 años de experiencia.",
        "hero_eyebrow": "Tecnología láser Fotona",
        "hero_h1_a": "Estética láser avanzada en", "hero_h1_accent": "Barcelona",
        "hero_lead": "En Impuls Longevity trabajamos con la tecnología láser Fotona StarWalker y SP Dynamis, líderes mundiales en estética avanzada. Tratamientos personalizados, resultados visibles, naturales y seguros.",
        "hero_cta1": "Pide tu cita", "hero_cta2": "Ver servicios",
        "trust": [("+15", "años de experiencia"), ("Fotona", "tecnología líder mundial"), ("100%", "protocolos personalizados")],
        "services_eyebrow": "Nuestros servicios",
        "services_h2": "Tratamientos láser para cada necesidad",
        "services_p": "Cada sesión está diseñada por especialistas certificados para ofrecerte resultados seguros y personalizados.",
        "wellness_eyebrow": "También en Impuls Longevity",
        "wellness_h2": "Salud y bienestar",
        "wellness_p": "Programas médicos de salud, control de peso y equilibrio hormonal, en un sitio dedicado.",
        "safety_eyebrow": "Seguridad y calidad",
        "safety_h2": "Resultados visibles, naturales y seguros",
        "safety_p": "Priorizamos la seguridad y la calidad en todos nuestros servicios. Nuestro equipo de especialistas certificados en estética y láser cuenta con formación avanzada y una amplia experiencia.",
        "safety_list": [
            "Diagnóstico previo y protocolo personalizado para cada piel.",
            "Tecnología Fotona, líder mundial en láseres médico-estéticos.",
            "Especialistas con más de 15 años de experiencia.",
        ],
        "tech_eyebrow": "Nuestra tecnología",
        "tech_h2": "Láseres Fotona de última generación",
        "tech_p": "Cada tipo de láser aporta una longitud de onda específica para tratar con precisión cada indicación.",
        "tech_items": [
            ("Q-Switched", "Fragmentación de pigmentos: tatuajes y manchas profundas."),
            ("Erbio:YAG", "Renovación de la superficie de la piel y textura."),
            ("Neodimio:YAG", "Tratamiento vascular, depilación y acción en profundidad."),
            ("Fraccional", "Estimulación del colágeno para cicatrices y rejuvenecimiento."),
        ],
        "why_eyebrow": "Por qué Impuls Longevity",
        "why_h2": "Por qué elegirnos",
        "why_items": [
            ("+15", "Años de experiencia", "Un equipo internacional con amplia trayectoria en estética láser."),
            ("Fotona", "Tecnología líder", "Trabajamos con StarWalker y SP Dynamis, referentes mundiales."),
            ("100%", "Protocolo personalizado", "Valoración previa y plan adaptado a tu piel en cada caso."),
            ("Barcelona", "En el centro", "Clínica en Plaza Urquinaona, en pleno corazón de la ciudad."),
        ],
        "faq_eyebrow": "Preguntas frecuentes",
        "faq_h2": "Antes de tu primera visita",
        "faq": [
            ("¿Dónde os encontráis?", "Nuestro centro está en Pl. d'Urquinaona, 6, Piso 14, A1 · 08010 Barcelona. En la página de contacto encontrarás el mapa y las rutas."),
            ("¿En qué ciudades trabajáis?", "De momento, nuestro centro ofrece servicios únicamente en Barcelona."),
            ("¿Es necesario reservar cita?", "Sí, es muy importante reservar cita previa para poder atenderte con la dedicación que mereces."),
            ("¿Cómo sé qué tratamiento necesito?", "En la primera visita realizamos una valoración de tu piel y diseñamos un protocolo personalizado según tu caso."),
        ],
    },
    "ca": {
        "title": "Impuls Longevity · Estètica làser avançada Fotona · Barcelona",
        "description": "Impuls Longevity — clínica d'estètica làser a Barcelona. Tecnologia Fotona StarWalker i SP Dynamis: aclariment de tatuatges, depilació, rejoveniment, acne i taques. Més de 15 anys d'experiència.",
        "hero_eyebrow": "Tecnologia làser Fotona",
        "hero_h1_a": "Estètica làser avançada a", "hero_h1_accent": "Barcelona",
        "hero_lead": "A Impuls Longevity treballem amb la tecnologia làser Fotona StarWalker i SP Dynamis, líders mundials en estètica avançada. Tractaments personalitzats, resultats visibles, naturals i segurs.",
        "hero_cta1": "Demana cita", "hero_cta2": "Veure serveis",
        "trust": [("+15", "anys d'experiència"), ("Fotona", "tecnologia líder mundial"), ("100%", "protocols personalitzats")],
        "services_eyebrow": "Els nostres serveis",
        "services_h2": "Tractaments làser per a cada necessitat",
        "services_p": "Cada sessió està dissenyada per especialistes certificats per oferir-te resultats segurs i personalitzats.",
        "wellness_eyebrow": "També a Impuls Longevity",
        "wellness_h2": "Salut i benestar",
        "wellness_p": "Programes mèdics de salut, control de pes i equilibri hormonal, en un lloc dedicat.",
        "safety_eyebrow": "Seguretat i qualitat",
        "safety_h2": "Resultats visibles, naturals i segurs",
        "safety_p": "Prioritzem la seguretat i la qualitat en tots els nostres serveis. El nostre equip d'especialistes certificats en estètica i làser compta amb formació avançada i una àmplia experiència.",
        "safety_list": [
            "Diagnòstic previ i protocol personalitzat per a cada pell.",
            "Tecnologia Fotona, líder mundial en làsers medicoestètics.",
            "Especialistes amb més de 15 anys d'experiència.",
        ],
        "tech_eyebrow": "La nostra tecnologia",
        "tech_h2": "Làsers Fotona d'última generació",
        "tech_p": "Cada tipus de làser aporta una longitud d'ona específica per tractar amb precisió cada indicació.",
        "tech_items": [
            ("Q-Switched", "Fragmentació de pigments: tatuatges i taques profundes."),
            ("Erbi:YAG", "Renovació de la superfície de la pell i textura."),
            ("Neodimi:YAG", "Tractament vascular, depilació i acció en profunditat."),
            ("Fraccional", "Estimulació del col·lagen per a cicatrius i rejoveniment."),
        ],
        "why_eyebrow": "Per què Impuls Longevity",
        "why_h2": "Per què triar-nos",
        "why_items": [
            ("+15", "Anys d'experiència", "Un equip internacional amb àmplia trajectòria en estètica làser."),
            ("Fotona", "Tecnologia líder", "Treballem amb StarWalker i SP Dynamis, referents mundials."),
            ("100%", "Protocol personalitzat", "Valoració prèvia i pla adaptat a la teva pell en cada cas."),
            ("Barcelona", "Al centre", "Clínica a la Plaça Urquinaona, al cor de la ciutat."),
        ],
        "faq_eyebrow": "Preguntes freqüents",
        "faq_h2": "Abans de la teva primera visita",
        "faq": [
            ("On esteu?", "El nostre centre és a Pl. d'Urquinaona, 6, Pis 14, A1 · 08010 Barcelona. A la pàgina de contacte hi trobaràs el mapa i les rutes."),
            ("En quines ciutats treballeu?", "De moment, el nostre centre ofereix serveis únicament a Barcelona."),
            ("Cal reservar cita?", "Sí, és molt important reservar cita prèvia per poder atendre't amb la dedicació que et mereixes."),
            ("Com sé quin tractament necessito?", "A la primera visita fem una valoració de la teva pell i dissenyem un protocol personalitzat segons el teu cas."),
        ],
    },
    "ru": {
        "title": "Impuls Longevity · Лазерная эстетика Fotona · Барселона",
        "description": "Impuls Longevity — клиника лазерной эстетики в Барселоне. Технология Fotona StarWalker и SP Dynamis: осветление тату, депиляция, омоложение, акне и пигментация. Более 15 лет опыта.",
        "hero_eyebrow": "Технология Fotona",
        "hero_h1_a": "Лазерная эстетика в", "hero_h1_accent": "Барселоне",
        "hero_lead": "В Impuls Longevity мы работаем на лазерах Fotona StarWalker и SP Dynamis — мировых лидерах эстетической медицины. Индивидуальные протоколы, заметный, естественный и безопасный результат.",
        "hero_cta1": "Записаться", "hero_cta2": "Все услуги",
        "trust": [("15+", "лет опыта"), ("Fotona", "мировой лидер"), ("100%", "индивидуальные протоколы")],
        "services_eyebrow": "Наши услуги",
        "services_h2": "Лазерные процедуры под любую задачу",
        "services_p": "Каждый сеанс разрабатывают сертифицированные специалисты — безопасно и индивидуально под вас.",
        "wellness_eyebrow": "Также в Impuls Longevity",
        "wellness_h2": "Здоровье и благополучие",
        "wellness_p": "Медицинские программы здоровья, контроля веса и гормонального баланса — на отдельном сайте.",
        "safety_eyebrow": "Безопасность и качество",
        "safety_h2": "Заметный, естественный и безопасный результат",
        "safety_p": "Мы ставим безопасность и качество во главу угла. Наша команда сертифицированных специалистов по эстетике и лазеру имеет продвинутую подготовку и большой опыт.",
        "safety_list": [
            "Предварительная диагностика и индивидуальный протокол для каждой кожи.",
            "Технология Fotona — мировой лидер медико-эстетических лазеров.",
            "Специалисты с опытом более 15 лет.",
        ],
        "tech_eyebrow": "Наши технологии",
        "tech_h2": "Лазеры Fotona нового поколения",
        "tech_p": "Каждый тип лазера даёт свою длину волны, чтобы точно работать с конкретной задачей.",
        "tech_items": [
            ("Q-Switched", "Дробление пигмента: тату и глубокая пигментация."),
            ("Erbium:YAG", "Обновление поверхности кожи и текстуры."),
            ("Neodymium:YAG", "Сосуды, депиляция и работа в глубине."),
            ("Фракционный", "Стимуляция коллагена для рубцов и омоложения."),
        ],
        "why_eyebrow": "Почему Impuls Longevity",
        "why_h2": "Почему выбирают нас",
        "why_items": [
            ("15+", "Лет опыта", "Международная команда с большим стажем в лазерной эстетике."),
            ("Fotona", "Технологии-лидеры", "Работаем на StarWalker и SP Dynamis — мировые эталоны."),
            ("100%", "Индивидуальный протокол", "Предварительная оценка и план под вашу кожу в каждом случае."),
            ("Barcelona", "В центре города", "Клиника на Plaza Urquinaona, в самом сердце Барселоны."),
        ],
        "faq_eyebrow": "Частые вопросы",
        "faq_h2": "Перед первым визитом",
        "faq": [
            ("Где вы находитесь?", "Наш центр: Pl. d'Urquinaona, 6, Piso 14, A1 · 08010 Barcelona. Карта и маршруты — на странице контактов."),
            ("В каких городах вы работаете?", "Сейчас центр принимает только в Барселоне."),
            ("Нужна ли предварительная запись?", "Да, запись обязательна — так мы уделим вам всё необходимое внимание."),
            ("Как понять, какая процедура мне нужна?", "На первом визите мы оцениваем состояние кожи и составляем индивидуальный протокол под ваш случай."),
        ],
    },
    "en": {
        "title": "Impuls Longevity · Advanced Fotona laser aesthetics · Barcelona",
        "description": "Impuls Longevity — laser aesthetics clinic in Barcelona. Fotona StarWalker & SP Dynamis technology: tattoo lightening, hair removal, rejuvenation, acne and pigmentation. 15+ years of experience.",
        "hero_eyebrow": "Fotona laser technology",
        "hero_h1_a": "Advanced laser aesthetics in", "hero_h1_accent": "Barcelona",
        "hero_lead": "At Impuls Longevity we work with Fotona StarWalker and SP Dynamis lasers, world leaders in advanced aesthetics. Personalised treatments with visible, natural and safe results.",
        "hero_cta1": "Book now", "hero_cta2": "See services",
        "trust": [("15+", "years of experience"), ("Fotona", "world-leading technology"), ("100%", "personalised protocols")],
        "services_eyebrow": "Our services",
        "services_h2": "Laser treatments for every need",
        "services_p": "Every session is designed by certified specialists to deliver safe, personalised results.",
        "wellness_eyebrow": "Also at Impuls Longevity",
        "wellness_h2": "Health and wellbeing",
        "wellness_p": "Medical programmes for health, weight control and hormonal balance, on a dedicated site.",
        "safety_eyebrow": "Safety & quality",
        "safety_h2": "Visible, natural and safe results",
        "safety_p": "We prioritise safety and quality across all our services. Our team of certified aesthetics and laser specialists has advanced training and extensive experience.",
        "safety_list": [
            "Prior assessment and a personalised protocol for every skin type.",
            "Fotona technology, a world leader in medical-aesthetic lasers.",
            "Specialists with over 15 years of experience.",
        ],
        "tech_eyebrow": "Our technology",
        "tech_h2": "Latest-generation Fotona lasers",
        "tech_p": "Each laser type delivers a specific wavelength to treat every indication with precision.",
        "tech_items": [
            ("Q-Switched", "Pigment fragmentation: tattoos and deep pigmentation."),
            ("Erbium:YAG", "Skin surface and texture renewal."),
            ("Neodymium:YAG", "Vascular treatment, hair removal and deep action."),
            ("Fractional", "Collagen stimulation for scars and rejuvenation."),
        ],
        "why_eyebrow": "Why Impuls Longevity",
        "why_h2": "Why choose us",
        "why_items": [
            ("15+", "Years of experience", "An international team with broad experience in laser aesthetics."),
            ("Fotona", "Leading technology", "We work with StarWalker and SP Dynamis, world benchmarks."),
            ("100%", "Personalised protocol", "Prior assessment and a plan adapted to your skin in every case."),
            ("Barcelona", "City centre", "Clinic at Plaza Urquinaona, in the heart of the city."),
        ],
        "faq_eyebrow": "FAQ",
        "faq_h2": "Before your first visit",
        "faq": [
            ("Where are you located?", "Our centre is at Pl. d'Urquinaona, 6, Floor 14, A1 · 08010 Barcelona. You'll find the map and directions on the contact page."),
            ("Which cities do you serve?", "For now, our centre operates in Barcelona only."),
            ("Do I need an appointment?", "Yes, booking in advance is important so we can give you the attention you deserve."),
            ("How do I know which treatment I need?", "At your first visit we assess your skin and design a personalised protocol for your case."),
        ],
    },
}

# ------------------------------------------------------------------
# Opiniones reales de pacientes (Google). Texto original en español;
# se muestran igual en todos los idiomas (no se traducen las citas).
# ------------------------------------------------------------------
REVIEWS = [
    {"name": "Edgar Miguel Rivera", "stars": 5,
     "text": "Excelente trato y atención muy buena, con mucho profesionalismo. Gracias, estoy satisfecho."},
    {"name": "Carlos Gálvez", "stars": 5,
     "text": "Llevo atendiéndome en la clínica más de 4 años y estoy muy contento, excelentes profesionales y bonitas instalaciones."},
    {"name": "Manuel Ignacio García Flores", "stars": 5,
     "text": "Personal altamente cualificado, muy profesionales, centro con tecnología de punta, trato agradable y en todo momento te explican las mejores opciones de tu caso. Los recomiendo. Lo que más me ha gustado es su ética profesional y honestidad en el manejo de los procedimientos; eso es importante para sentirse en confianza."},
    {"name": "Maritza Avendaño", "stars": 5,
     "text": "Maravilloso espacio, la recepción es muy atenta y cordial. El equipo humano es profesional y atento. Solo llevo 2 sesiones pero el trato y el equipo está genial. He venido desde Gerona a Barcelona solo para verles y merece la pena."},
]

REVIEW_UI = {
    "es": {"eyebrow": "Opiniones", "h2": "Lo que dicen nuestros pacientes",
           "note": "Opiniones reales de pacientes en Google. Los resultados de cada tratamiento pueden variar según la persona.", "src": "en Google"},
    "ca": {"eyebrow": "Opinions", "h2": "El que diuen els nostres pacients",
           "note": "Opinions reals de pacients a Google. Els resultats de cada tractament poden variar segons la persona.", "src": "a Google"},
    "ru": {"eyebrow": "Отзывы", "h2": "Что говорят наши пациенты",
           "note": "Настоящие отзывы пациентов из Google. Результаты каждой процедуры индивидуальны и зависят от человека.", "src": "в Google"},
    "en": {"eyebrow": "Reviews", "h2": "What our patients say",
           "note": "Genuine patient reviews from Google. Results of each treatment may vary from person to person.", "src": "on Google"},
}
