# -*- coding: utf-8 -*-
"""
Impuls Longevity — datos de las 10 páginas de servicio en ES / RU / EN.
Cada servicio: slug, imagen, y por idioma: name, tag, intro[], benefits[],
steps[(titulo, desc)], tech[], faq[(q, a)].
"""

SERVICES = [
    {
        "slug": "eliminacion-de-tatuajes",
        "img": "/assets/svc-eliminacion-de-tatuajes.jpg",
        "img2": "/assets/tattoo-back.jpg",
        "es": {
            "name": "Aclaración de tatuajes",
            "tag": "Láser Q-Switched que aclara el tatuaje sin dañar la piel",
            "intro": [
                "Aclaramos tatuajes de forma progresiva y segura con láser Q-Switched, que emite pulsos ultracortos capaces de fragmentar las partículas de tinta sin agredir la piel de alrededor.",
                "El número de sesiones depende del tamaño, la antigüedad, los colores y la profundidad de la tinta. En la valoración inicial estimamos tu plan personalizado.",
            ],
            "benefits": ["Fragmenta tintas de varios colores", "Respeta la piel circundante", "Protocolo adaptado a cada tatuaje", "Realizado por especialistas certificados"],
            "steps": [("Valoración", "Analizamos el tatuaje y tu piel y estimamos el número de sesiones."), ("Sesiones láser", "El láser fragmenta la tinta, que el organismo elimina de forma natural."), ("Cuidado y resultado", "Te damos pautas de cuidado entre sesiones para un resultado óptimo.")],
            "tech": ["Láser Q-Switched", "Neodimio:YAG"],
            "faq": [("¿Duele el tratamiento?", "Se percibe una molestia tolerable; adaptamos la comodidad durante la sesión."), ("¿Cuántas sesiones necesito?", "Varía según el tatuaje; lo estimamos en la valoración inicial.")],
        },
        "ca": {
            "name": "Aclariment de tatuatges",
            "tag": "Làser Q-Switched que aclareix el tatuatge sense danyar la pell",
            "intro": [
                "Aclarim tatuatges de manera progressiva i segura amb làser Q-Switched, que emet polsos ultracurts capaços de fragmentar les partícules de tinta sense agredir la pell del voltant.",
                "El nombre de sessions depèn de la mida, l'antiguitat, els colors i la profunditat de la tinta. A la valoració inicial estimem el teu pla personalitzat.",
            ],
            "benefits": ["Fragmenta tintes de diversos colors", "Respecta la pell circumdant", "Protocol adaptat a cada tatuatge", "Realitzat per especialistes certificats"],
            "steps": [("Valoració", "Analitzem el tatuatge i la teva pell i estimem el nombre de sessions."), ("Sessions làser", "El làser fragmenta la tinta, que l'organisme elimina de manera natural."), ("Cura i resultat", "Et donem pautes de cura entre sessions per a un resultat òptim.")],
            "tech": ["Làser Q-Switched", "Neodimi:YAG"],
            "faq": [("Fa mal el tractament?", "Es percep una molèstia tolerable; adaptem la comoditat durant la sessió."), ("Quantes sessions necessito?", "Varia segons el tatuatge; ho estimem a la valoració inicial.")],
        },
        "ru": {
            "name": "Осветление тату",
            "tag": "Лазер Q-Switched осветляет татуировку, не повреждая кожу",
            "intro": [
                "Осветляем татуировки постепенно и безопасно лазером Q-Switched: сверхкороткие импульсы дробят частицы пигмента, не травмируя окружающую кожу.",
                "Количество сеансов зависит от размера, давности, цветов и глубины пигмента. Индивидуальный план составляем на первой консультации.",
            ],
            "benefits": ["Дробит пигмент разных цветов", "Бережёт окружающую кожу", "Протокол под каждую татуировку", "Выполняют сертифицированные специалисты"],
            "steps": [("Консультация", "Оцениваем татуировку и кожу, прогнозируем число сеансов."), ("Сеансы лазера", "Лазер дробит пигмент, организм выводит его естественно."), ("Уход и результат", "Даём рекомендации между сеансами для лучшего результата.")],
            "tech": ["Лазер Q-Switched", "Neodymium:YAG"],
            "faq": [("Это больно?", "Ощущается терпимый дискомфорт; заботимся о комфорте во время сеанса."), ("Сколько нужно сеансов?", "Зависит от татуировки; оценим на первой консультации.")],
        },
        "en": {
            "name": "Tattoo lightening",
            "tag": "Q-Switched laser that lightens the tattoo without harming the skin",
            "intro": [
                "We lighten tattoos gradually and safely with a Q-Switched laser: ultra-short pulses shatter the ink particles without damaging the surrounding skin.",
                "The number of sessions depends on size, age, colours and ink depth. We estimate your personalised plan at the initial assessment.",
            ],
            "benefits": ["Shatters multi-colour inks", "Protects surrounding skin", "Protocol tailored to each tattoo", "Performed by certified specialists"],
            "steps": [("Assessment", "We analyse the tattoo and your skin and estimate the number of sessions."), ("Laser sessions", "The laser breaks up the ink, which the body clears naturally."), ("Care & result", "We provide aftercare guidance between sessions for the best result.")],
            "tech": ["Q-Switched laser", "Neodymium:YAG"],
            "faq": [("Does it hurt?", "There is a tolerable sensation; we keep you comfortable throughout."), ("How many sessions do I need?", "It varies by tattoo; we estimate this at the initial assessment.")],
        },
    },
    {
        "slug": "rejuvenecimiento-cutaneo",
        "img": "/assets/svc-rejuvenecimiento-cutaneo.jpg",
        "img2": "/assets/svc2-rejuvenecimiento-cutaneo.jpg",
        "es": {
            "name": "Rejuvenecimiento cutáneo",
            "tag": "Estimula el colágeno para una piel más firme y luminosa",
            "intro": [
                "El rejuvenecimiento láser estimula la producción natural de colágeno, mejorando la firmeza, la luminosidad y la uniformidad del tono sin cirugía.",
                "Es un tratamiento progresivo: los resultados aparecen de forma natural a lo largo de las semanas siguientes a cada sesión.",
            ],
            "benefits": ["Mayor firmeza y elasticidad", "Piel más luminosa y uniforme", "Sin cirugía ni tiempo de baja", "Resultados naturales y progresivos"],
            "steps": [("Valoración", "Estudiamos tu piel y tus objetivos."), ("Sesiones", "El láser estimula el colágeno en profundidad."), ("Mantenimiento", "Planificamos sesiones de mantenimiento según tu piel.")],
            "tech": ["Er:YAG", "Nd:YAG", "Láser Fraccional"],
            "faq": [("¿Cuándo veré resultados?", "De forma progresiva en las semanas posteriores a cada sesión."), ("¿Puedo hacer vida normal?", "Sí, es un tratamiento sin tiempo de baja.")],
        },
        "ca": {
            "name": "Rejoveniment cutani",
            "tag": "Estimula el col·lagen per a una pell més ferma i lluminosa",
            "intro": [
                "El rejoveniment làser estimula la producció natural de col·lagen, millorant la fermesa, la lluminositat i la uniformitat del to sense cirurgia.",
                "És un tractament progressiu: els resultats apareixen de manera natural al llarg de les setmanes següents a cada sessió.",
            ],
            "benefits": ["Més fermesa i elasticitat", "Pell més lluminosa i uniforme", "Sense cirurgia ni temps de baixa", "Resultats naturals i progressius"],
            "steps": [("Valoració", "Estudiem la teva pell i els teus objectius."), ("Sessions", "El làser estimula el col·lagen en profunditat."), ("Manteniment", "Planifiquem sessions de manteniment segons la teva pell.")],
            "tech": ["Er:YAG", "Nd:YAG", "Làser Fraccional"],
            "faq": [("Quan veuré resultats?", "De manera progressiva a les setmanes posteriors a cada sessió."), ("Puc fer vida normal?", "Sí, és un tractament sense temps de baixa.")],
        },
        "ru": {
            "name": "Омоложение кожи",
            "tag": "Стимулирует коллаген — кожа плотнее и сияет",
            "intro": [
                "Лазерное омоложение стимулирует естественную выработку коллагена, повышая плотность, сияние и ровность тона кожи — без хирургии.",
                "Это постепенная процедура: результат проявляется естественно в течение недель после каждого сеанса.",
            ],
            "benefits": ["Плотность и упругость", "Сияющая, ровная кожа", "Без хирургии и простоя", "Естественный, постепенный результат"],
            "steps": [("Консультация", "Изучаем кожу и ваши цели."), ("Сеансы", "Лазер стимулирует коллаген в глубине."), ("Поддержание", "Планируем поддерживающие сеансы под вашу кожу.")],
            "tech": ["Er:YAG", "Nd:YAG", "Фракционный лазер"],
            "faq": [("Когда виден результат?", "Постепенно, в недели после каждого сеанса."), ("Можно вести обычную жизнь?", "Да, процедура без простоя.")],
        },
        "en": {
            "name": "Skin rejuvenation",
            "tag": "Stimulates collagen for firmer, more radiant skin",
            "intro": [
                "Laser rejuvenation stimulates natural collagen production, improving firmness, radiance and an even tone — without surgery.",
                "It is a progressive treatment: results appear naturally over the weeks following each session.",
            ],
            "benefits": ["Greater firmness and elasticity", "More radiant, even skin", "No surgery, no downtime", "Natural, progressive results"],
            "steps": [("Assessment", "We study your skin and your goals."), ("Sessions", "The laser stimulates collagen deep within the skin."), ("Maintenance", "We plan maintenance sessions to suit your skin.")],
            "tech": ["Er:YAG", "Nd:YAG", "Fractional laser"],
            "faq": [("When will I see results?", "Progressively, in the weeks after each session."), ("Can I resume normal life?", "Yes, this treatment has no downtime.")],
        },
    },
    {
        "slug": "eliminacion-de-pigmentacion",
        "img": "/assets/svc-eliminacion-de-pigmentacion.jpg",
        "img2": "/assets/pigment-face.jpg",
        "es": {
            "name": "Aclaración de pigmentación",
            "tag": "Manchas solares y de la edad para un tono homogéneo",
            "intro": [
                "Tratamos manchas solares, léntigos y otras hiperpigmentaciones con láser selectivo, que actúa sobre el exceso de melanina sin dañar la piel sana.",
                "El resultado es un tono más uniforme y luminoso. Diseñamos el protocolo según el tipo y la profundidad de las manchas.",
            ],
            "benefits": ["Reduce manchas solares y de la edad", "Tono más homogéneo", "Actúa sobre la melanina sobrante", "Protocolo según tu tipo de piel"],
            "steps": [("Valoración", "Identificamos el tipo de mancha y tu fototipo."), ("Sesiones láser", "El láser dirige su energía al pigmento."), ("Resultado", "La mancha se aclara de forma progresiva.")],
            "tech": ["Q-Switched", "Er:YAG"],
            "faq": [("¿Volverán las manchas?", "Con protección solar adecuada el resultado se mantiene mejor."), ("¿Es apto para toda piel?", "Valoramos tu fototipo para elegir el protocolo seguro.")],
        },
        "ca": {
            "name": "Aclariment de pigmentació",
            "tag": "Taques solars i de l'edat per a un to homogeni",
            "intro": [
                "Tractem taques solars, lentígens i altres hiperpigmentacions amb làser selectiu, que actua sobre l'excés de melanina sense danyar la pell sana.",
                "El resultat és un to més uniforme i lluminós. Dissenyem el protocol segons el tipus i la profunditat de les taques.",
            ],
            "benefits": ["Redueix taques solars i de l'edat", "To més homogeni", "Actua sobre la melanina sobrant", "Protocol segons el teu tipus de pell"],
            "steps": [("Valoració", "Identifiquem el tipus de taca i el teu fototip."), ("Sessions làser", "El làser dirigeix la seva energia al pigment."), ("Resultat", "La taca s'aclareix de manera progressiva.")],
            "tech": ["Q-Switched", "Er:YAG"],
            "faq": [("Tornaran les taques?", "Amb protecció solar adequada el resultat es manté millor."), ("És apte per a tota pell?", "Valorem el teu fototip per triar el protocol segur.")],
        },
        "ru": {
            "name": "Осветление пигментации",
            "tag": "Солнечные и возрастные пятна — ровный тон",
            "intro": [
                "Работаем с солнечными пятнами, лентиго и другой гиперпигментацией селективным лазером: он действует на избыток меланина, не повреждая здоровую кожу.",
                "Результат — более ровный и сияющий тон. Протокол подбираем по типу и глубине пятен.",
            ],
            "benefits": ["Уменьшает солнечные и возрастные пятна", "Более ровный тон", "Действует на избыток меланина", "Протокол под ваш тип кожи"],
            "steps": [("Консультация", "Определяем тип пятен и ваш фототип."), ("Сеансы лазера", "Лазер направляет энергию на пигмент."), ("Результат", "Пятно постепенно светлеет.")],
            "tech": ["Q-Switched", "Er:YAG"],
            "faq": [("Пятна вернутся?", "С правильной защитой от солнца результат держится лучше."), ("Подходит любой коже?", "Оцениваем фототип и выбираем безопасный протокол.")],
        },
        "en": {
            "name": "Pigmentation lightening",
            "tag": "Sun and age spots for an even skin tone",
            "intro": [
                "We treat sun spots, lentigines and other hyperpigmentation with a selective laser that targets excess melanin without harming healthy skin.",
                "The result is a more even, radiant tone. We design the protocol according to the type and depth of the spots.",
            ],
            "benefits": ["Reduces sun and age spots", "More even skin tone", "Targets excess melanin", "Protocol for your skin type"],
            "steps": [("Assessment", "We identify the spot type and your skin phototype."), ("Laser sessions", "The laser directs its energy to the pigment."), ("Result", "The spot lightens progressively.")],
            "tech": ["Q-Switched", "Er:YAG"],
            "faq": [("Will the spots come back?", "With proper sun protection the result lasts better."), ("Is it suitable for all skin?", "We assess your phototype to choose a safe protocol.")],
        },
    },
    {
        "slug": "depilacion-laser",
        "img": "/assets/svc-depilacion-laser.jpg",
        "img2": "/assets/depil-2.jpg",
        "es": {
            "name": "Depilación láser",
            "tag": "Reducción del vello duradera, cómoda y segura",
            "intro": [
                "La depilación láser reduce el vello de forma progresiva y duradera, actuando sobre el folículo en su fase de crecimiento con total seguridad.",
                "Es apta para distintas zonas del cuerpo y tipos de piel. Planificamos las sesiones según tu ciclo de vello.",
            ],
            "benefits": ["Reducción duradera del vello", "Cómoda y segura", "Apta para distintas zonas", "Piel más suave y sin irritación"],
            "steps": [("Valoración", "Analizamos la zona, el vello y tu piel."), ("Sesiones", "El láser actúa sobre el folículo activo."), ("Mantenimiento", "Sesiones espaciadas para consolidar el resultado.")],
            "tech": ["Nd:YAG"],
            "faq": [("¿Cuántas sesiones hacen falta?", "Depende de la zona y el tipo de vello; lo vemos en la valoración."), ("¿Es segura en piel morena?", "Con Nd:YAG adaptamos el tratamiento a distintos fototipos.")],
        },
        "ca": {
            "name": "Depilació làser",
            "tag": "Reducció del pèl duradora, còmoda i segura",
            "intro": [
                "La depilació làser redueix el pèl de manera progressiva i duradora, actuant sobre el fol·licle en la seva fase de creixement amb total seguretat.",
                "És apta per a diferents zones del cos i tipus de pell. Planifiquem les sessions segons el teu cicle de pèl.",
            ],
            "benefits": ["Reducció duradora del pèl", "Còmoda i segura", "Apta per a diferents zones", "Pell més suau i sense irritació"],
            "steps": [("Valoració", "Analitzem la zona, el pèl i la teva pell."), ("Sessions", "El làser actua sobre el fol·licle actiu."), ("Manteniment", "Sessions espaiades per consolidar el resultat.")],
            "tech": ["Nd:YAG"],
            "faq": [("Quantes sessions calen?", "Depèn de la zona i el tipus de pèl; ho veiem a la valoració."), ("És segura en pell morena?", "Amb Nd:YAG adaptem el tractament a diferents fototips.")],
        },
        "ru": {
            "name": "Лазерная депиляция",
            "tag": "Долговременное, комфортное и безопасное удаление волос",
            "intro": [
                "Лазерная депиляция постепенно и надолго сокращает рост волос, воздействуя на фолликул в фазе роста — полностью безопасно.",
                "Подходит для разных зон тела и типов кожи. Сеансы планируем под ваш цикл роста волос.",
            ],
            "benefits": ["Долговременное сокращение волос", "Комфортно и безопасно", "Разные зоны тела", "Гладкая кожа без раздражения"],
            "steps": [("Консультация", "Анализируем зону, волосы и кожу."), ("Сеансы", "Лазер работает по активному фолликулу."), ("Поддержание", "Сеансы с интервалом закрепляют результат.")],
            "tech": ["Nd:YAG"],
            "faq": [("Сколько нужно сеансов?", "Зависит от зоны и типа волос; определим на консультации."), ("Безопасно ли для смуглой кожи?", "С Nd:YAG адаптируем процедуру под разные фототипы.")],
        },
        "en": {
            "name": "Laser hair removal",
            "tag": "Long-lasting, comfortable and safe hair reduction",
            "intro": [
                "Laser hair removal reduces hair progressively and durably, acting on the follicle during its growth phase with full safety.",
                "It is suitable for various body areas and skin types. We plan sessions around your hair cycle.",
            ],
            "benefits": ["Long-lasting hair reduction", "Comfortable and safe", "Suitable for various areas", "Smoother skin without irritation"],
            "steps": [("Assessment", "We analyse the area, the hair and your skin."), ("Sessions", "The laser acts on the active follicle."), ("Maintenance", "Spaced sessions consolidate the result.")],
            "tech": ["Nd:YAG"],
            "faq": [("How many sessions are needed?", "It depends on the area and hair type; we assess this first."), ("Is it safe on darker skin?", "With Nd:YAG we adapt the treatment to different phototypes.")],
        },
    },
    {
        "slug": "tratamiento-del-acne",
        "img": "/assets/svc-tratamiento-del-acne.jpg",
        "img2": "/assets/svc2-depilacion-laser.jpg",
        "es": {
            "name": "Tratamiento del acné",
            "tag": "Reduce la actividad sebácea y las marcas del acné",
            "intro": [
                "El láser ayuda a controlar el acné activo reduciendo la actividad de las glándulas sebáceas y la carga bacteriana, y mejora las marcas y cicatrices que deja.",
                "Combinamos protocolos según el tipo de acné y el estado de tu piel para un resultado equilibrado.",
            ],
            "benefits": ["Reduce el acné activo", "Mejora marcas y cicatrices", "Menos brillo y poro más fino", "Protocolo según tu piel"],
            "steps": [("Valoración", "Evaluamos el tipo de acné y tu piel."), ("Sesiones láser", "Actuamos sobre la glándula y las marcas."), ("Resultado", "Piel más equilibrada y uniforme.")],
            "tech": ["Nd:YAG", "Láser Fraccional"],
            "faq": [("¿Sirve para el acné activo y las marcas?", "Sí, adaptamos el protocolo a cada objetivo."), ("¿Se combina con otros cuidados?", "Podemos integrarlo en una rutina dermatológica.")],
        },
        "ca": {
            "name": "Tractament de l'acne",
            "tag": "Redueix l'activitat sebàcia i les marques de l'acne",
            "intro": [
                "El làser ajuda a controlar l'acne actiu reduint l'activitat de les glàndules sebàcies i la càrrega bacteriana, i millora les marques i cicatrius que deixa.",
                "Combinem protocols segons el tipus d'acne i l'estat de la teva pell per a un resultat equilibrat.",
            ],
            "benefits": ["Redueix l'acne actiu", "Millora marques i cicatrius", "Menys brillantor i porus més fi", "Protocol segons la teva pell"],
            "steps": [("Valoració", "Avaluem el tipus d'acne i la teva pell."), ("Sessions làser", "Actuem sobre la glàndula i les marques."), ("Resultat", "Pell més equilibrada i uniforme.")],
            "tech": ["Nd:YAG", "Làser Fraccional"],
            "faq": [("Serveix per a l'acne actiu i les marques?", "Sí, adaptem el protocol a cada objectiu."), ("Es combina amb altres cures?", "Podem integrar-ho en una rutina dermatològica.")],
        },
        "ru": {
            "name": "Лечение акне",
            "tag": "Снижает активность сальных желёз и следы акне",
            "intro": [
                "Лазер помогает контролировать активное акне, снижая активность сальных желёз и бактериальную нагрузку, а также улучшает следы и рубцы.",
                "Комбинируем протоколы по типу акне и состоянию кожи для сбалансированного результата.",
            ],
            "benefits": ["Уменьшает активное акне", "Улучшает следы и рубцы", "Меньше жирного блеска, уже поры", "Протокол под вашу кожу"],
            "steps": [("Консультация", "Оцениваем тип акне и кожу."), ("Сеансы лазера", "Работаем по железе и следам."), ("Результат", "Более ровная, сбалансированная кожа.")],
            "tech": ["Nd:YAG", "Фракционный лазер"],
            "faq": [("Помогает и при активном акне, и при следах?", "Да, адаптируем протокол под задачу."), ("Сочетается с другим уходом?", "Можем встроить в дерматологическую рутину.")],
        },
        "en": {
            "name": "Acne treatment",
            "tag": "Reduces sebaceous activity and acne marks",
            "intro": [
                "The laser helps control active acne by reducing sebaceous gland activity and bacterial load, and improves the marks and scars it leaves behind.",
                "We combine protocols according to the acne type and your skin condition for a balanced result.",
            ],
            "benefits": ["Reduces active acne", "Improves marks and scars", "Less shine, refined pores", "Protocol for your skin"],
            "steps": [("Assessment", "We evaluate the acne type and your skin."), ("Laser sessions", "We act on the gland and the marks."), ("Result", "More balanced, even skin.")],
            "tech": ["Nd:YAG", "Fractional laser"],
            "faq": [("Does it work for active acne and marks?", "Yes, we adapt the protocol to each goal."), ("Can it combine with other care?", "We can integrate it into a dermatological routine.")],
        },
    },
    {
        "slug": "aranas-vasculares-rosacea",
        "img": "/assets/svc-aranas-vasculares-rosacea.jpg",
        "img2": "/assets/clinic-facial.jpg",
        "es": {
            "name": "Arañas vasculares y rosácea",
            "tag": "Cierra capilares dilatados y reduce el enrojecimiento",
            "intro": [
                "El láser vascular actúa de forma selectiva sobre los capilares dilatados y el enrojecimiento de la rosácea, cerrando los vasos sin afectar a la piel sana.",
                "Es un tratamiento preciso que mejora visiblemente el aspecto de la piel reactiva y las arañas vasculares.",
            ],
            "benefits": ["Reduce arañas vasculares", "Menos enrojecimiento y rojeces", "Acción selectiva sobre el vaso", "Piel de aspecto más calmado"],
            "steps": [("Valoración", "Analizamos los vasos y tu tipo de piel."), ("Sesiones láser", "El láser cierra los capilares tratados."), ("Resultado", "El enrojecimiento se atenúa progresivamente.")],
            "tech": ["Nd:YAG"],
            "faq": [("¿Es doloroso?", "Se percibe una molestia breve y tolerable."), ("¿Cuántas sesiones?", "Depende de la extensión; lo estimamos en la valoración.")],
        },
        "ca": {
            "name": "Aranyes vasculars i rosàcia",
            "tag": "Tanca capil·lars dilatats i redueix l'envermelliment",
            "intro": [
                "El làser vascular actua de manera selectiva sobre els capil·lars dilatats i l'envermelliment de la rosàcia, tancant els vasos sense afectar la pell sana.",
                "És un tractament precís que millora visiblement l'aspecte de la pell reactiva i les aranyes vasculars.",
            ],
            "benefits": ["Redueix aranyes vasculars", "Menys envermelliment i rojors", "Acció selectiva sobre el vas", "Pell d'aspecte més calmat"],
            "steps": [("Valoració", "Analitzem els vasos i el teu tipus de pell."), ("Sessions làser", "El làser tanca els capil·lars tractats."), ("Resultat", "L'envermelliment s'atenua progressivament.")],
            "tech": ["Nd:YAG"],
            "faq": [("És dolorós?", "Es percep una molèstia breu i tolerable."), ("Quantes sessions?", "Depèn de l'extensió; ho estimem a la valoració.")],
        },
        "ru": {
            "name": "Сосудистые звёздочки и розацеа",
            "tag": "Закрывает расширенные капилляры, убирает покраснение",
            "intro": [
                "Сосудистый лазер избирательно действует на расширенные капилляры и покраснение при розацеа, закрывая сосуды без вреда для здоровой кожи.",
                "Это точная процедура, которая заметно улучшает вид реактивной кожи и сосудистых звёздочек.",
            ],
            "benefits": ["Убирает сосудистые звёздочки", "Меньше покраснений", "Избирательно по сосуду", "Более спокойный вид кожи"],
            "steps": [("Консультация", "Анализируем сосуды и тип кожи."), ("Сеансы лазера", "Лазер закрывает обработанные капилляры."), ("Результат", "Покраснение постепенно уходит.")],
            "tech": ["Nd:YAG"],
            "faq": [("Это больно?", "Ощущается краткий терпимый дискомфорт."), ("Сколько сеансов?", "Зависит от площади; оценим на консультации.")],
        },
        "en": {
            "name": "Spider veins & rosacea",
            "tag": "Closes dilated capillaries and reduces redness",
            "intro": [
                "The vascular laser acts selectively on dilated capillaries and rosacea redness, closing the vessels without affecting healthy skin.",
                "It is a precise treatment that visibly improves the appearance of reactive skin and spider veins.",
            ],
            "benefits": ["Reduces spider veins", "Less redness and flushing", "Selective vessel action", "Calmer-looking skin"],
            "steps": [("Assessment", "We analyse the vessels and your skin type."), ("Laser sessions", "The laser closes the treated capillaries."), ("Result", "Redness fades progressively.")],
            "tech": ["Nd:YAG"],
            "faq": [("Is it painful?", "A brief, tolerable sensation is felt."), ("How many sessions?", "It depends on the extent; we estimate at assessment.")],
        },
    },
    {
        "slug": "cicatrices-y-estrias",
        "img": "/assets/svc-cicatrices-y-estrias.jpg",
        "img2": "/assets/fotona-device.jpg",
        "es": {
            "name": "Cicatrices y estrías",
            "tag": "Láser fraccional que mejora textura y suaviza marcas",
            "intro": [
                "El láser fraccional renueva la piel por microzonas, estimulando el colágeno para mejorar la textura y suavizar cicatrices y estrías.",
                "Es eficaz en cicatrices de acné, quirúrgicas y estrías, con un enfoque progresivo y personalizado.",
            ],
            "benefits": ["Suaviza cicatrices y estrías", "Mejora la textura de la piel", "Estimula colágeno nuevo", "Resultados progresivos"],
            "steps": [("Valoración", "Estudiamos la cicatriz o estría y tu piel."), ("Sesiones", "El láser fraccional renueva la zona."), ("Resultado", "La textura mejora de forma progresiva.")],
            "tech": ["Láser Fraccional", "Er:YAG"],
            "faq": [("¿Funciona en estrías antiguas?", "Mejora textura y color; lo valoramos según el caso."), ("¿Cuántas sesiones?", "Depende de la zona y el tipo de marca.")],
        },
        "ca": {
            "name": "Cicatrius i estries",
            "tag": "Làser fraccional que millora la textura i suavitza les marques",
            "intro": [
                "El làser fraccional renova la pell per microzones, estimulant el col·lagen per millorar la textura i suavitzar cicatrius i estries.",
                "És eficaç en cicatrius d'acne, quirúrgiques i estries, amb un enfocament progressiu i personalitzat.",
            ],
            "benefits": ["Suavitza cicatrius i estries", "Millora la textura de la pell", "Estimula col·lagen nou", "Resultats progressius"],
            "steps": [("Valoració", "Estudiem la cicatriu o estria i la teva pell."), ("Sessions", "El làser fraccional renova la zona."), ("Resultat", "La textura millora de manera progressiva.")],
            "tech": ["Làser Fraccional", "Er:YAG"],
            "faq": [("Funciona en estries antigues?", "Millora textura i color; ho valorem segons el cas."), ("Quantes sessions?", "Depèn de la zona i el tipus de marca.")],
        },
        "ru": {
            "name": "Рубцы и растяжки",
            "tag": "Фракционный лазер улучшает текстуру и сглаживает следы",
            "intro": [
                "Фракционный лазер обновляет кожу микрозонами, стимулируя коллаген, чтобы улучшить текстуру и сгладить рубцы и растяжки.",
                "Эффективен при рубцах постакне, послеоперационных и растяжках — постепенный, индивидуальный подход.",
            ],
            "benefits": ["Сглаживает рубцы и растяжки", "Улучшает текстуру кожи", "Стимулирует новый коллаген", "Постепенный результат"],
            "steps": [("Консультация", "Изучаем рубец/растяжку и кожу."), ("Сеансы", "Фракционный лазер обновляет зону."), ("Результат", "Текстура улучшается постепенно.")],
            "tech": ["Фракционный лазер", "Er:YAG"],
            "faq": [("Работает на старых растяжках?", "Улучшает текстуру и цвет; оцениваем по случаю."), ("Сколько сеансов?", "Зависит от зоны и типа следа.")],
        },
        "en": {
            "name": "Scars & stretch marks",
            "tag": "Fractional laser that improves texture and softens marks",
            "intro": [
                "The fractional laser renews the skin in micro-zones, stimulating collagen to improve texture and soften scars and stretch marks.",
                "It is effective on acne, surgical scars and stretch marks, with a progressive, personalised approach.",
            ],
            "benefits": ["Softens scars and stretch marks", "Improves skin texture", "Stimulates new collagen", "Progressive results"],
            "steps": [("Assessment", "We study the scar or stretch mark and your skin."), ("Sessions", "The fractional laser renews the area."), ("Result", "Texture improves progressively.")],
            "tech": ["Fractional laser", "Er:YAG"],
            "faq": [("Does it work on old stretch marks?", "It improves texture and colour; we assess each case."), ("How many sessions?", "It depends on the area and mark type.")],
        },
    },
    {
        "slug": "onicomicosis",
        "img": "/assets/svc-onicomicosis.jpg",
        "img2": "/assets/svc2-cicatrices-y-estrias.jpg",
        "es": {
            "name": "Onicomicosis (hongos)",
            "tag": "Tratamiento láser de los hongos de las uñas",
            "intro": [
                "El láser trata la onicomicosis actuando por calor sobre el hongo de la uña, sin necesidad de fármacos orales prolongados.",
                "Es una opción cómoda y segura; el número de sesiones depende del grado de afectación de la uña.",
            ],
            "benefits": ["Actúa sobre el hongo de la uña", "Sin fármacos orales prolongados", "Cómodo y seguro", "Protocolo según el grado"],
            "steps": [("Valoración", "Evaluamos el estado de la uña."), ("Sesiones láser", "El calor del láser actúa sobre el hongo."), ("Seguimiento", "Revisamos la uña sana según crece.")],
            "tech": ["Nd:YAG"],
            "faq": [("¿Cuántas sesiones necesito?", "Depende del grado; lo estimamos en la valoración."), ("¿Es doloroso?", "Se percibe calor tolerable durante la sesión.")],
        },
        "ca": {
            "name": "Onicomicosi (fongs)",
            "tag": "Tractament làser dels fongs de les ungles",
            "intro": [
                "El làser tracta l'onicomicosi actuant per calor sobre el fong de l'ungla, sense necessitat de fàrmacs orals prolongats.",
                "És una opció còmoda i segura; el nombre de sessions depèn del grau d'afectació de l'ungla.",
            ],
            "benefits": ["Actua sobre el fong de l'ungla", "Sense fàrmacs orals prolongats", "Còmode i segur", "Protocol segons el grau"],
            "steps": [("Valoració", "Avaluem l'estat de l'ungla."), ("Sessions làser", "La calor del làser actua sobre el fong."), ("Seguiment", "Revisem l'ungla sana a mesura que creix.")],
            "tech": ["Nd:YAG"],
            "faq": [("Quantes sessions necessito?", "Depèn del grau; ho estimem a la valoració."), ("És dolorós?", "Es percep calor tolerable durant la sessió.")],
        },
        "ru": {
            "name": "Онихомикоз (грибок ногтей)",
            "tag": "Лазерное лечение грибка ногтей",
            "intro": [
                "Лазер лечит онихомикоз, воздействуя теплом на грибок ногтя — без длительного приёма таблеток.",
                "Это удобный и безопасный вариант; число сеансов зависит от степени поражения ногтя.",
            ],
            "benefits": ["Действует на грибок ногтя", "Без долгих таблеток", "Удобно и безопасно", "Протокол по степени поражения"],
            "steps": [("Консультация", "Оцениваем состояние ногтя."), ("Сеансы лазера", "Тепло лазера действует на грибок."), ("Наблюдение", "Контролируем отрастание здорового ногтя.")],
            "tech": ["Nd:YAG"],
            "faq": [("Сколько нужно сеансов?", "Зависит от степени; оценим на консультации."), ("Это больно?", "Ощущается терпимое тепло во время сеанса.")],
        },
        "en": {
            "name": "Onychomycosis (nail fungus)",
            "tag": "Laser treatment for nail fungus",
            "intro": [
                "The laser treats onychomycosis by acting with heat on the nail fungus, without the need for prolonged oral medication.",
                "It is a comfortable, safe option; the number of sessions depends on how affected the nail is.",
            ],
            "benefits": ["Acts on the nail fungus", "No prolonged oral medication", "Comfortable and safe", "Protocol by severity"],
            "steps": [("Assessment", "We evaluate the state of the nail."), ("Laser sessions", "The laser heat acts on the fungus."), ("Follow-up", "We review the healthy nail as it grows.")],
            "tech": ["Nd:YAG"],
            "faq": [("How many sessions do I need?", "It depends on severity; we estimate at assessment."), ("Is it painful?", "A tolerable warmth is felt during the session.")],
        },
    },
    {
        "slug": "rejuvenecimiento-4d-fotona",
        "img": "/assets/benefits.jpg",
        "external": "https://4dfotona.es/",  # sitio separado (como en el original)
        "es": {
            "name": "Rejuvenecimiento 4D Fotona",
            "tag": "Efecto lifting sin cirugía, dentro y fuera de la piel",
            "intro": [
                "El protocolo Fotona 4D combina varios modos de láser para trabajar la piel desde el interior de la boca y desde el exterior, logrando un efecto tensor y de rejuvenecimiento global.",
                "Es un tratamiento no invasivo, sin cirugía ni tiempo de baja, que mejora firmeza, contorno y luminosidad.",
            ],
            "benefits": ["Efecto lifting sin cirugía", "Trabaja dentro y fuera de la piel", "Mejora firmeza y contorno", "Sin tiempo de baja"],
            "steps": [("Valoración", "Estudiamos tu rostro y objetivos."), ("Protocolo 4D", "Aplicamos los modos de láser Fotona."), ("Resultado", "Firmeza y luminosidad progresivas.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("¿Es una cirugía?", "No, es un tratamiento láser no invasivo."), ("¿Cuántas sesiones?", "Diseñamos el plan en la valoración inicial.")],
        },
        "ca": {
            "name": "Rejoveniment 4D Fotona",
            "tag": "Efecte lifting sense cirurgia, dins i fora de la pell",
            "intro": [
                "El protocol Fotona 4D combina diversos modes de làser per treballar la pell des de l'interior de la boca i des de l'exterior, aconseguint un efecte tensor i de rejoveniment global.",
                "És un tractament no invasiu, sense cirurgia ni temps de baixa, que millora fermesa, contorn i lluminositat.",
            ],
            "benefits": ["Efecte lifting sense cirurgia", "Treballa dins i fora de la pell", "Millora fermesa i contorn", "Sense temps de baixa"],
            "steps": [("Valoració", "Estudiem el teu rostre i objectius."), ("Protocol 4D", "Apliquem els modes de làser Fotona."), ("Resultat", "Fermesa i lluminositat progressives.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("És una cirurgia?", "No, és un tractament làser no invasiu."), ("Quantes sessions?", "Dissenyem el pla a la valoració inicial.")],
        },
        "ru": {
            "name": "Омоложение 4D Fotona",
            "tag": "Эффект лифтинга без хирургии — снаружи и изнутри",
            "intro": [
                "Протокол Fotona 4D сочетает несколько режимов лазера, работая с кожей изнутри полости рта и снаружи, создавая подтягивающий эффект и общее омоложение.",
                "Это неинвазивная процедура — без хирургии и простоя — улучшающая плотность, контур и сияние.",
            ],
            "benefits": ["Лифтинг без хирургии", "Работа снаружи и изнутри", "Плотность и контур", "Без простоя"],
            "steps": [("Консультация", "Изучаем лицо и цели."), ("Протокол 4D", "Применяем режимы лазера Fotona."), ("Результат", "Плотность и сияние нарастают.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Это операция?", "Нет, это неинвазивная лазерная процедура."), ("Сколько сеансов?", "План составим на первой консультации.")],
        },
        "en": {
            "name": "Fotona 4D rejuvenation",
            "tag": "Non-surgical lifting effect, inside and out",
            "intro": [
                "The Fotona 4D protocol combines several laser modes to work the skin both from inside the mouth and from the outside, achieving a tightening and overall rejuvenation effect.",
                "It is a non-invasive treatment, with no surgery or downtime, improving firmness, contour and radiance.",
            ],
            "benefits": ["Non-surgical lifting effect", "Works inside and outside the skin", "Improves firmness and contour", "No downtime"],
            "steps": [("Assessment", "We study your face and goals."), ("4D protocol", "We apply the Fotona laser modes."), ("Result", "Progressive firmness and radiance.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Is it surgery?", "No, it is a non-invasive laser treatment."), ("How many sessions?", "We design the plan at the initial assessment.")],
        },
    },
    {
        "slug": "eliminacion-de-neoplasias",
        "img": "/assets/proc-hand-1.jpg",
        "img2": "/assets/svc2-eliminacion-de-neoplasias.jpg",
        "es": {
            "name": "Eliminación de lesiones cutáneas",
            "tag": "Retirada precisa de lesiones benignas de la piel",
            "intro": [
                "Retiramos con láser lesiones cutáneas benignas —como verrugas, fibromas o pequeñas lesiones— de forma precisa y con buena cicatrización.",
                "Toda lesión se valora previamente; si procede, se deriva a estudio médico antes de cualquier actuación.",
            ],
            "benefits": ["Retirada precisa de la lesión", "Buena cicatrización", "Valoración médica previa", "Procedimiento cómodo"],
            "steps": [("Valoración", "Examinamos la lesión y decidimos el enfoque."), ("Procedimiento láser", "Retiramos la lesión con precisión."), ("Cuidado", "Pautas de cuidado para una cicatrización óptima.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("¿Cualquier lesión se puede tratar?", "Solo lesiones benignas y tras valoración; si hay dudas, se estudia médicamente."), ("¿Deja marca?", "Buscamos la mejor cicatrización posible con cuidados adecuados.")],
        },
        "ca": {
            "name": "Eliminació de lesions cutànies",
            "tag": "Retirada precisa de lesions benignes de la pell",
            "intro": [
                "Retirem amb làser lesions cutànies benignes —com berrugues, fibromes o petites lesions— de manera precisa i amb bona cicatrització.",
                "Tota lesió es valora prèviament; si escau, es deriva a estudi mèdic abans de qualsevol actuació.",
            ],
            "benefits": ["Retirada precisa de la lesió", "Bona cicatrització", "Valoració mèdica prèvia", "Procediment còmode"],
            "steps": [("Valoració", "Examinem la lesió i decidim l'enfocament."), ("Procediment làser", "Retirem la lesió amb precisió."), ("Cura", "Pautes de cura per a una cicatrització òptima.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Qualsevol lesió es pot tractar?", "Només lesions benignes i després de valoració; si hi ha dubtes, s'estudia mèdicament."), ("Deixa marca?", "Busquem la millor cicatrització possible amb cures adequades.")],
        },
        "ru": {
            "name": "Удаление кожных образований",
            "tag": "Точное удаление доброкачественных образований кожи",
            "intro": [
                "Удаляем лазером доброкачественные образования кожи — бородавки, фибромы, небольшие элементы — точно и с хорошим заживлением.",
                "Каждое образование сначала оценивается; при необходимости направляем на медицинское обследование до любых действий.",
            ],
            "benefits": ["Точное удаление образования", "Хорошее заживление", "Предварительная оценка врача", "Комфортная процедура"],
            "steps": [("Консультация", "Осматриваем образование и выбираем подход."), ("Лазерная процедура", "Удаляем элемент с точностью."), ("Уход", "Рекомендации для оптимального заживления.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Любое образование можно удалить?", "Только доброкачественные и после оценки; при сомнениях — медицинское обследование."), ("Останется след?", "Стремимся к лучшему заживлению при правильном уходе.")],
        },
        "en": {
            "name": "Skin lesion removal",
            "tag": "Precise removal of benign skin lesions",
            "intro": [
                "We remove benign skin lesions with laser — such as warts, fibromas or small lesions — precisely and with good healing.",
                "Every lesion is assessed beforehand; where appropriate, it is referred for medical review before any procedure.",
            ],
            "benefits": ["Precise lesion removal", "Good healing", "Prior medical assessment", "Comfortable procedure"],
            "steps": [("Assessment", "We examine the lesion and decide the approach."), ("Laser procedure", "We remove the lesion with precision."), ("Care", "Aftercare guidance for optimal healing.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Can any lesion be treated?", "Only benign lesions and after assessment; if in doubt, it is medically reviewed."), ("Will it leave a mark?", "We aim for the best possible healing with proper care.")],
        },
    },
    {
        "slug": "smas-lifting",
        "img": "/assets/svc-smas-lifting.jpg",
        "img2": "/assets/svc2-smas-lifting.jpg",
        "external": "https://smaslifting.es/",
        "es": {
            "name": "SMAS Lifting",
            "tag": "Lifting facial no invasivo con láser Fotona",
            "intro": [
                "El SMAS Lifting es un procedimiento moderno que reafirma la piel y ayuda a preservar su juventud, con tecnología láser Fotona que actúa sobre las capas profundas de la piel.",
                "Estimula la producción de colágeno para mejorar la firmeza y reducir las arrugas, sin cirugía, de forma cómoda y con un efecto duradero.",
            ],
            "benefits": ["Reafirma la piel del rostro", "Reduce las arrugas", "Efecto lifting sin cirugía", "Resultados duraderos y naturales"],
            "steps": [("Valoración", "Estudiamos tu piel y tus objetivos."), ("Sesiones láser", "El láser Fotona actúa en profundidad estimulando el colágeno."), ("Resultado", "La firmeza mejora de forma progresiva.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("¿Es doloroso?", "Es un tratamiento cómodo, sin necesidad de anestesia."), ("¿Cuántas sesiones necesito?", "Depende de tu piel y objetivos; lo definimos en la valoración.")],
        },
        "ca": {
            "name": "SMAS Lifting",
            "tag": "Lifting facial no invasiu amb làser Fotona",
            "intro": [
                "El SMAS Lifting és un procediment modern que reafirma la pell i ajuda a preservar-ne la joventut, amb tecnologia làser Fotona que actua sobre les capes profundes de la pell.",
                "Estimula la producció de col·lagen per millorar la fermesa i reduir les arrugues, sense cirurgia, de manera còmoda i amb un efecte durador.",
            ],
            "benefits": ["Reafirma la pell del rostre", "Redueix les arrugues", "Efecte lifting sense cirurgia", "Resultats duradors i naturals"],
            "steps": [("Valoració", "Estudiem la teva pell i els teus objectius."), ("Sessions làser", "El làser Fotona actua en profunditat estimulant el col·lagen."), ("Resultat", "La fermesa millora de manera progressiva.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("És dolorós?", "És un tractament còmode, sense necessitat d'anestèsia."), ("Quantes sessions necessito?", "Depèn de la teva pell i objectius; ho definim a la valoració.")],
        },
        "ru": {
            "name": "SMAS-лифтинг",
            "tag": "Неинвазивный лифтинг лица лазером Fotona",
            "intro": [
                "SMAS-лифтинг — современная процедура, которая уплотняет кожу и помогает сохранить молодость: лазер Fotona воздействует на глубокие слои кожи.",
                "Стимулирует выработку коллагена, повышая упругость и уменьшая морщины, без хирургии, комфортно и с длительным эффектом.",
            ],
            "benefits": ["Уплотняет кожу лица", "Уменьшает морщины", "Эффект лифтинга без хирургии", "Долгий и естественный результат"],
            "steps": [("Консультация", "Изучаем кожу и ваши цели."), ("Сеансы лазера", "Fotona работает в глубине, стимулируя коллаген."), ("Результат", "Упругость нарастает постепенно.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Это больно?", "Процедура комфортная, анестезия не нужна."), ("Сколько нужно сеансов?", "Зависит от кожи и целей; определим на консультации.")],
        },
        "en": {
            "name": "SMAS Lifting",
            "tag": "Non-invasive facial lifting with Fotona laser",
            "intro": [
                "SMAS Lifting is a modern procedure that firms the skin and helps preserve its youth, using Fotona laser technology that acts on the deep layers of the skin.",
                "It stimulates collagen production to improve firmness and reduce wrinkles, without surgery, comfortably and with a long-lasting effect.",
            ],
            "benefits": ["Firms the facial skin", "Reduces wrinkles", "Lifting effect without surgery", "Durable, natural results"],
            "steps": [("Assessment", "We study your skin and goals."), ("Laser sessions", "The Fotona laser works deep, stimulating collagen."), ("Result", "Firmness improves progressively.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Is it painful?", "It's a comfortable treatment, no anaesthesia needed."), ("How many sessions do I need?", "It depends on your skin and goals; we define it at the assessment.")],
        },
    },
    {
        "slug": "fotona-4glow",
        "img": "/assets/clinic-facial.jpg",
        "img2": "/assets/svc2-rejuvenecimiento-cutaneo.jpg",
        "external": "https://fotona4glow.es/",
        "es": {
            "name": "Fotona 4Glow",
            "tag": "Rejuvenecimiento facial 4 en 1, sin agujas ni cirugía",
            "intro": [
                "Fotona 4Glow es un tratamiento de rejuvenecimiento facial que combina de forma sinérgica las dos longitudes de onda del láser Fotona (Er:YAG y Nd:YAG) en cuatro modos, tratando varias capas de la piel en una sola sesión.",
                "Es un protocolo no invasivo, sin tiempo de recuperación, que mejora la firmeza, el tono, la textura y la luminosidad a la vez.",
            ],
            "benefits": ["Sin agujas ni cirugía", "Sin tiempo de recuperación", "Estimula el colágeno", "Firmeza, tono, textura y luminosidad"],
            "steps": [("SMOOTH", "Calentamiento profundo para efecto lifting."), ("FRAC3 · PIANO", "Trabaja pigmentación, líneas finas y dermis."), ("SupErficial", "Peeling ligero para un brillo final.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("¿Duele?", "Es un tratamiento cómodo, descrito como un calor agradable."), ("¿Necesito recuperación?", "No, puedes retomar tu rutina el mismo día.")],
        },
        "ca": {
            "name": "Fotona 4Glow",
            "tag": "Rejoveniment facial 4 en 1, sense agulles ni cirurgia",
            "intro": [
                "Fotona 4Glow és un tractament de rejoveniment facial que combina de manera sinèrgica les dues longituds d'ona del làser Fotona (Er:YAG i Nd:YAG) en quatre modes, tractant diverses capes de la pell en una sola sessió.",
                "És un protocol no invasiu, sense temps de baixa, que millora la fermesa, el to, la textura i la lluminositat alhora.",
            ],
            "benefits": ["Sense agulles ni cirurgia", "Sense temps de baixa", "Estimula el col·lagen", "Fermesa, to, textura i lluminositat"],
            "steps": [("SMOOTH", "Escalfament profund per a efecte lifting."), ("FRAC3 · PIANO", "Treballa pigmentació, línies fines i dermis."), ("SupErficial", "Peeling lleuger per a una lluïssor final.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Fa mal?", "És un tractament còmode, descrit com una calor agradable."), ("Necessito recuperació?", "No, pots reprendre la teva rutina el mateix dia.")],
        },
        "ru": {
            "name": "Fotona 4Glow",
            "tag": "Омоложение лица 4-в-1, без игл и хирургии",
            "intro": [
                "Fotona 4Glow — процедура омоложения лица, синергично сочетающая две длины волны лазера Fotona (Er:YAG и Nd:YAG) в четырёх режимах, прорабатывая несколько слоёв кожи за один сеанс.",
                "Это неинвазивный протокол без периода восстановления, который одновременно улучшает упругость, тон, текстуру и сияние.",
            ],
            "benefits": ["Без игл и хирургии", "Без периода восстановления", "Стимулирует коллаген", "Упругость, тон, текстура и сияние"],
            "steps": [("SMOOTH", "Глубокий прогрев для эффекта лифтинга."), ("FRAC3 · PIANO", "Работа с пигментом, мелкими линиями и дермой."), ("SupErficial", "Лёгкий пилинг для финального сияния.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Это больно?", "Комфортно, ощущается как приятное тепло."), ("Нужно восстановление?", "Нет, можно вернуться к делам в тот же день.")],
        },
        "en": {
            "name": "Fotona 4Glow",
            "tag": "4-in-1 facial rejuvenation, no needles or surgery",
            "intro": [
                "Fotona 4Glow is a facial rejuvenation treatment that synergistically combines the two Fotona laser wavelengths (Er:YAG and Nd:YAG) in four modes, treating several layers of the skin in a single session.",
                "It is a non-invasive protocol with no downtime that improves firmness, tone, texture and radiance at once.",
            ],
            "benefits": ["No needles or surgery", "No downtime", "Stimulates collagen", "Firmness, tone, texture and radiance"],
            "steps": [("SMOOTH", "Deep heating for a lifting effect."), ("FRAC3 · PIANO", "Works on pigmentation, fine lines and dermis."), ("SupErficial", "A light peel for a final glow.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Does it hurt?", "It's comfortable, described as a pleasant warmth."), ("Do I need recovery time?", "No, you can resume your routine the same day.")],
        },
    },
    {
        "slug": "control-de-peso",
        "group": "wellness",
        "external": "https://adelgazarnatural.es/",
        "es": {"name": "Control de peso", "tag": "Adelgazar con seguimiento médico"},
        "ca": {"name": "Control de pes", "tag": "Aprimar amb seguiment mèdic"},
        "ru": {"name": "Контроль веса", "tag": "Похудение под контролем врача"},
        "en": {"name": "Weight control", "tag": "Weight loss with medical supervision"},
    },
    {
        "slug": "salud-de-la-mujer",
        "group": "wellness",
        "external": "https://adelgazarnatural.es/salud-mujer.html",
        "es": {"name": "Salud de la mujer", "tag": "Equilibrio hormonal y bienestar"},
        "ca": {"name": "Salut de la dona", "tag": "Equilibri hormonal i benestar"},
        "ru": {"name": "Женское здоровье", "tag": "Гормональный баланс и самочувствие"},
        "en": {"name": "Women's health", "tag": "Hormonal balance and wellbeing"},
    },
    {
        "slug": "salud-del-hombre",
        "group": "wellness",
        "external": "https://adelgazarnatural.es/salud-hombre.html",
        "es": {"name": "Salud del hombre", "tag": "Equilibrio hormonal y energía"},
        "ca": {"name": "Salut de l'home", "tag": "Equilibri hormonal i energia"},
        "ru": {"name": "Мужское здоровье", "tag": "Гормональный баланс и энергия"},
        "en": {"name": "Men's health", "tag": "Hormonal balance and energy"},
    },
]
