# -*- coding: utf-8 -*-
"""
Impuls Longevity — datos de las 10 páginas de servicio en ES / RU / EN.
Cada servicio: slug, imagen, y por idioma: name, tag, intro[], benefits[],
steps[(titulo, desc)], tech[], faq[(q, a)].
"""

SERVICES = [
    {
        "slug": "eliminacion-de-tatuajes",
        "img": "/assets/svc-eliminacion-de-tatuajes.jpg",
        "img2": "/assets/tattoo-back.jpg",
        "es": {
            "name": "Aclaración de tatuajes",
            "tag": "Láser Q-Switched que aclara el tatuaje sin dañar la piel",
            "intro": [
                "Aclaramos tatuajes de forma progresiva y segura con láser Q-Switched, que emite pulsos ultracortos capaces de fragmentar las partículas de tinta sin agredir la piel de alrededor.",
                "El número de sesiones depende del tamaño, la antigüedad, los colores y la profundidad de la tinta. En la valoración inicial estimamos tu plan personalizado.",
            ],
            "benefits": ["Fragmenta tintas de varios colores", "Respeta la piel circundante", "Protocolo adaptado a cada tatuaje", "Realizado por especialistas certificados"],
            "steps": [("Valoración", "Analizamos el tatuaje y tu piel y estimamos el número de sesiones."), ("Sesiones láser", "El láser fragmenta la tinta, que el organismo elimina de forma natural."), ("Cuidado y resultado", "Te damos pautas de cuidado entre sesiones para un resultado óptimo.")],
            "tech": ["Láser Q-Switched", "Neodimio:YAG"],
            "faq": [
                ("¿Cuántas sesiones necesito?", "No damos una cifra «a ojo»: cada tatuaje y cada piel reaccionan de forma distinta. En la valoración inicial, con un cuestionario y una pequeña prueba de láser, definimos un rango realista según tu caso y tu objetivo."),
                ("¿Cuánto cuesta?", "Seguimos el mismo principio de transparencia: el precio real por sesión se indica tras valorar la piel y comprobar cómo reacciona al láser. Es la única forma de darte una cifra honesta y no una estimación al azar."),
                ("¿Duele el tratamiento?", "Se percibe una molestia tolerable. Cuidamos tu comodidad durante toda la sesión y adaptamos el protocolo a tu piel."),
                ("¿Se elimina del todo? ¿Quedará cicatriz?", "El objetivo es aclarar o eliminar el tatuaje de forma progresiva cuidando la piel. Valoramos la zona previamente para minimizar riesgos; los resultados varían según cada tatuaje y cada persona, por eso trabajamos con una valoración individualizada."),
                ("¿Cuánto tiempo dura el proceso?", "Es un tratamiento progresivo de varias sesiones espaciadas algunas semanas, para que la piel se recupere entre una y otra. El plan concreto se ajusta en la valoración inicial."),
            ],
        },
        "ca": {
            "name": "Aclariment de tatuatges",
            "tag": "Làser Q-Switched que aclareix el tatuatge sense danyar la pell",
            "intro": [
                "Aclarim tatuatges de manera progressiva i segura amb làser Q-Switched, que emet polsos ultracurts capaços de fragmentar les partícules de tinta sense agredir la pell del voltant.",
                "El nombre de sessions depèn de la mida, l'antiguitat, els colors i la profunditat de la tinta. A la valoració inicial estimem el teu pla personalitzat.",
            ],
            "benefits": ["Fragmenta tintes de diversos colors", "Respecta la pell circumdant", "Protocol adaptat a cada tatuatge", "Realitzat per especialistes certificats"],
            "steps": [("Valoració", "Analitzem el tatuatge i la teva pell i estimem el nombre de sessions."), ("Sessions làser", "El làser fragmenta la tinta, que l'organisme elimina de manera natural."), ("Cura i resultat", "Et donem pautes de cura entre sessions per a un resultat òptim.")],
            "tech": ["Làser Q-Switched", "Neodimi:YAG"],
            "faq": [
                ("Quantes sessions necessito?", "No donem una xifra «a ull»: cada tatuatge i cada pell reaccionen de manera diferent. A la valoració inicial, amb un qüestionari i una petita prova de làser, definim un rang realista segons el teu cas i el teu objectiu."),
                ("Quant costa?", "Seguim el mateix principi de transparència: el preu real per sessió s'indica després de valorar la pell i comprovar com reacciona al làser. És l'única manera de donar-te una xifra honesta i no una estimació a l'atzar."),
                ("Fa mal el tractament?", "Es percep una molèstia tolerable. Tenim cura de la teva comoditat durant tota la sessió i adaptem el protocol a la teva pell."),
                ("S'elimina del tot? Quedarà cicatriu?", "L'objectiu és aclarir o eliminar el tatuatge de manera progressiva tenint cura de la pell. Valorem la zona prèviament per minimitzar riscos; els resultats varien segons cada tatuatge i cada persona, per això treballem amb una valoració individualitzada."),
                ("Quant dura el procés?", "És un tractament progressiu de diverses sessions espaiades algunes setmanes, perquè la pell es recuperi entre una i altra. El pla concret s'ajusta a la valoració inicial."),
            ],
        },
        "ru": {
            "name": "Осветление тату",
            "tag": "Лазер Q-Switched осветляет татуировку, не повреждая кожу",
            "intro": [
                "Осветляем татуировки постепенно и безопасно лазером Q-Switched: сверхкороткие импульсы дробят частицы пигмента, не травмируя окружающую кожу.",
                "Количество сеансов зависит от размера, давности, цветов и глубины пигмента. Индивидуальный план составляем на первой консультации.",
            ],
            "benefits": ["Дробит пигмент разных цветов", "Бережёт окружающую кожу", "Протокол под каждую татуировку", "Выполняют сертифицированные специалисты"],
            "steps": [("Консультация", "Оцениваем татуировку и кожу, прогнозируем число сеансов."), ("Сеансы лазера", "Лазер дробит пигмент, организм выводит его естественно."), ("Уход и результат", "Даём рекомендации между сеансами для лучшего результата.")],
            "tech": ["Лазер Q-Switched", "Neodymium:YAG"],
            "faq": [
                ("Сколько нужно сеансов?", "Мы не называем цифру «на глаз»: каждая татуировка и кожа реагируют по-разному. На первой консультации — с опросником и небольшим пробным тестом лазера — определяем реалистичный диапазон под ваш случай и цель."),
                ("Сколько это стоит?", "Тот же принцип честности: реальную цену за сеанс называем после оценки кожи и проверки, как она реагирует на лазер. Только так можно дать честную цифру, а не наугад."),
                ("Это больно?", "Ощущается терпимый дискомфорт. Заботимся о вашем комфорте на протяжении всего сеанса и подбираем протокол под вашу кожу."),
                ("Уйдёт ли татуировка полностью? Останется ли шрам?", "Цель — постепенно осветлить или удалить татуировку, бережно относясь к коже. Предварительно оцениваем зону, чтобы снизить риски; результат зависит от конкретной татуировки и человека, поэтому работаем через индивидуальную оценку."),
                ("Сколько длится весь процесс?", "Это постепенное лечение из нескольких сеансов с интервалом в несколько недель, чтобы кожа восстанавливалась между ними. Точный план определяем на первой консультации."),
            ],
        },
        "en": {
            "name": "Tattoo lightening",
            "tag": "Q-Switched laser that lightens the tattoo without harming the skin",
            "intro": [
                "We lighten tattoos gradually and safely with a Q-Switched laser: ultra-short pulses shatter the ink particles without damaging the surrounding skin.",
                "The number of sessions depends on size, age, colours and ink depth. We estimate your personalised plan at the initial assessment.",
            ],
            "benefits": ["Shatters multi-colour inks", "Protects surrounding skin", "Protocol tailored to each tattoo", "Performed by certified specialists"],
            "steps": [("Assessment", "We analyse the tattoo and your skin and estimate the number of sessions."), ("Laser sessions", "The laser breaks up the ink, which the body clears naturally."), ("Care & result", "We provide aftercare guidance between sessions for the best result.")],
            "tech": ["Q-Switched laser", "Neodymium:YAG"],
            "faq": [
                ("How many sessions do I need?", "We don't give a number «by eye»: every tattoo and every skin reacts differently. At the initial assessment, with a questionnaire and a small laser test, we define a realistic range based on your case and your goal."),
                ("How much does it cost?", "We follow the same transparency principle: the real price per session is given after assessing the skin and checking how it reacts to the laser. It's the only way to give you an honest figure rather than a random estimate."),
                ("Does the treatment hurt?", "There is a tolerable sensation. We keep you comfortable throughout the session and adapt the protocol to your skin."),
                ("Will it be removed completely? Will there be a scar?", "The aim is to lighten or remove the tattoo gradually while protecting the skin. We assess the area beforehand to minimise risks; results vary by tattoo and person, which is why we work with an individualised assessment."),
                ("How long does the whole process take?", "It's a gradual treatment of several sessions spaced a few weeks apart, so the skin recovers between them. The specific plan is set at the initial assessment."),
            ],
        },
    },
    {
        "slug": "rejuvenecimiento-cutaneo",
        "img": "/assets/svc-rejuvenecimiento-cutaneo.jpg",
        "img2": "/assets/svc2-rejuvenecimiento-cutaneo.jpg",
        "es": {
            "name": "Rejuvenecimiento cutáneo",
            "tag": "Estimula el colágeno para una piel más firme y luminosa",
            "intro": [
                "El rejuvenecimiento láser estimula la producción natural de colágeno, mejorando la firmeza, la luminosidad y la uniformidad del tono sin cirugía.",
                "Es un tratamiento progresivo: los resultados aparecen de forma natural a lo largo de las semanas siguientes a cada sesión.",
            ],
            "benefits": ["Mayor firmeza y elasticidad", "Piel más luminosa y uniforme", "Sin cirugía ni tiempo de baja", "Resultados naturales y progresivos"],
            "steps": [("Valoración", "Estudiamos tu piel y tus objetivos."), ("Sesiones", "El láser estimula el colágeno en profundidad."), ("Mantenimiento", "Planificamos sesiones de mantenimiento según tu piel.")],
            "tech": ["Er:YAG", "Nd:YAG", "Láser Fraccional"],
            "faq": [
                ("¿Cuántas sesiones necesito?", "Depende del estado de tu piel y de tus objetivos. Normalmente se plantea un plan de varias sesiones espaciadas; el número concreto se define en la valoración inicial."),
                ("¿Cuándo veré resultados?", "De forma progresiva en las semanas posteriores a cada sesión, a medida que la piel produce colágeno nuevo."),
                ("¿Es doloroso? ¿Tiene tiempo de baja?", "Es un tratamiento cómodo y sin tiempo de baja: puedes retomar tu rutina el mismo día."),
                ("¿Cuánto cuesta?", "El precio se ajusta al plan que necesita tu piel, por eso lo indicamos tras la valoración. Así te damos una cifra realista y no una estimación al azar."),
                ("¿Es apto para cualquier tipo de piel?", "Valoramos tu fototipo y el estado de la piel para adaptar el láser de forma segura en nuestro centro de Barcelona."),
            ],
        },
        "ca": {
            "name": "Rejoveniment cutani",
            "tag": "Estimula el col·lagen per a una pell més ferma i lluminosa",
            "intro": [
                "El rejoveniment làser estimula la producció natural de col·lagen, millorant la fermesa, la lluminositat i la uniformitat del to sense cirurgia.",
                "És un tractament progressiu: els resultats apareixen de manera natural al llarg de les setmanes següents a cada sessió.",
            ],
            "benefits": ["Més fermesa i elasticitat", "Pell més lluminosa i uniforme", "Sense cirurgia ni temps de baixa", "Resultats naturals i progressius"],
            "steps": [("Valoració", "Estudiem la teva pell i els teus objectius."), ("Sessions", "El làser estimula el col·lagen en profunditat."), ("Manteniment", "Planifiquem sessions de manteniment segons la teva pell.")],
            "tech": ["Er:YAG", "Nd:YAG", "Làser Fraccional"],
            "faq": [
                ("Quantes sessions necessito?", "Depèn de l'estat de la teva pell i dels teus objectius. Normalment es planteja un pla de diverses sessions espaiades; el nombre concret es defineix a la valoració inicial."),
                ("Quan veuré resultats?", "De manera progressiva a les setmanes posteriors a cada sessió, a mesura que la pell produeix col·lagen nou."),
                ("Fa mal? Té temps de baixa?", "És un tractament còmode i sense temps de baixa: pots reprendre la teva rutina el mateix dia."),
                ("Quant costa?", "El preu s'ajusta al pla que necessita la teva pell, per això l'indiquem després de la valoració. Així et donem una xifra realista i no una estimació a l'atzar."),
                ("És apte per a qualsevol tipus de pell?", "Valorem el teu fototip i l'estat de la pell per adaptar el làser de manera segura al nostre centre de Barcelona."),
            ],
        },
        "ru": {
            "name": "Омоложение кожи",
            "tag": "Стимулирует коллаген — кожа плотнее и сияет",
            "intro": [
                "Лазерное омоложение стимулирует естественную выработку коллагена, повышая плотность, сияние и ровность тона кожи — без хирургии.",
                "Это постепенная процедура: результат проявляется естественно в течение недель после каждого сеанса.",
            ],
            "benefits": ["Плотность и упругость", "Сияющая, ровная кожа", "Без хирургии и простоя", "Естественный, постепенный результат"],
            "steps": [("Консультация", "Изучаем кожу и ваши цели."), ("Сеансы", "Лазер стимулирует коллаген в глубине."), ("Поддержание", "Планируем поддерживающие сеансы под вашу кожу.")],
            "tech": ["Er:YAG", "Nd:YAG", "Фракционный лазер"],
            "faq": [
                ("Сколько нужно сеансов?", "Зависит от состояния кожи и ваших целей. Обычно предлагается план из нескольких сеансов с интервалом; точное число определяем на первой консультации."),
                ("Когда виден результат?", "Постепенно в недели после каждого сеанса, по мере выработки нового коллагена."),
                ("Это больно? Есть период восстановления?", "Процедура комфортная и без простоя: вернуться к делам можно в тот же день."),
                ("Сколько это стоит?", "Цена зависит от плана, который нужен вашей коже, поэтому называем её после консультации. Так мы даём реалистичную цифру, а не наугад."),
                ("Подходит ли любой коже?", "Мы оцениваем фототип и состояние кожи, чтобы безопасно настроить лазер в нашем центре в Барселоне."),
            ],
        },
        "en": {
            "name": "Skin rejuvenation",
            "tag": "Stimulates collagen for firmer, more radiant skin",
            "intro": [
                "Laser rejuvenation stimulates natural collagen production, improving firmness, radiance and an even tone — without surgery.",
                "It is a progressive treatment: results appear naturally over the weeks following each session.",
            ],
            "benefits": ["Greater firmness and elasticity", "More radiant, even skin", "No surgery, no downtime", "Natural, progressive results"],
            "steps": [("Assessment", "We study your skin and your goals."), ("Sessions", "The laser stimulates collagen deep within the skin."), ("Maintenance", "We plan maintenance sessions to suit your skin.")],
            "tech": ["Er:YAG", "Nd:YAG", "Fractional laser"],
            "faq": [
                ("How many sessions do I need?", "It depends on your skin condition and goals. A plan of several spaced sessions is usually proposed; the exact number is set at the initial assessment."),
                ("When will I see results?", "Progressively in the weeks after each session, as the skin produces new collagen."),
                ("Is it painful? Is there downtime?", "It is a comfortable treatment with no downtime: you can resume your routine the same day."),
                ("How much does it cost?", "The price depends on the plan your skin needs, so we give it after the assessment. That way you get a realistic figure rather than a random estimate."),
                ("Is it suitable for any skin type?", "We assess your phototype and skin condition to adapt the laser safely at our Barcelona clinic."),
            ],
        },
    },
    {
        "slug": "eliminacion-de-pigmentacion",
        "img": "/assets/svc-eliminacion-de-pigmentacion.jpg",
        "img2": "/assets/pigment-face.jpg",
        "es": {
            "name": "Aclaración de pigmentación",
            "tag": "Manchas solares y de la edad para un tono homogéneo",
            "intro": [
                "Tratamos manchas solares, léntigos y otras hiperpigmentaciones con láser selectivo, que actúa sobre el exceso de melanina sin dañar la piel sana.",
                "El resultado es un tono más uniforme y luminoso. Diseñamos el protocolo según el tipo y la profundidad de las manchas.",
            ],
            "benefits": ["Reduce manchas solares y de la edad", "Tono más homogéneo", "Actúa sobre la melanina sobrante", "Protocolo según tu tipo de piel"],
            "steps": [("Valoración", "Identificamos el tipo de mancha y tu fototipo."), ("Sesiones láser", "El láser dirige su energía al pigmento."), ("Resultado", "La mancha se aclara de forma progresiva.")],
            "tech": ["Q-Switched", "Er:YAG"],
            "faq": [
                ("¿Cuántas sesiones necesito?", "Depende del tipo, la cantidad y la profundidad de las manchas y de tu fototipo. Se suele plantear un plan de varias sesiones que definimos en la valoración."),
                ("¿Volverán las manchas?", "El láser aclara la mancha existente, pero la piel puede volver a pigmentar con el sol. Con una buena protección solar el resultado se mantiene mejor."),
                ("¿Cuándo veré resultados?", "Tras cada sesión la mancha se oscurece ligeramente y luego se aclara en los días siguientes; la mejora es progresiva."),
                ("¿Es doloroso?", "Se percibe una molestia breve y tolerable, sin apenas tiempo de recuperación."),
                ("¿Cuánto cuesta?", "El precio depende del número y tipo de manchas, por eso lo indicamos tras valorar tu piel en nuestro centro de Barcelona."),
            ],
        },
        "ca": {
            "name": "Aclariment de pigmentació",
            "tag": "Taques solars i de l'edat per a un to homogeni",
            "intro": [
                "Tractem taques solars, lentígens i altres hiperpigmentacions amb làser selectiu, que actua sobre l'excés de melanina sense danyar la pell sana.",
                "El resultat és un to més uniforme i lluminós. Dissenyem el protocol segons el tipus i la profunditat de les taques.",
            ],
            "benefits": ["Redueix taques solars i de l'edat", "To més homogeni", "Actua sobre la melanina sobrant", "Protocol segons el teu tipus de pell"],
            "steps": [("Valoració", "Identifiquem el tipus de taca i el teu fototip."), ("Sessions làser", "El làser dirigeix la seva energia al pigment."), ("Resultat", "La taca s'aclareix de manera progressiva.")],
            "tech": ["Q-Switched", "Er:YAG"],
            "faq": [
                ("Quantes sessions necessito?", "Depèn del tipus, la quantitat i la profunditat de les taques i del teu fototip. Se sol plantejar un pla de diverses sessions que definim a la valoració."),
                ("Tornaran les taques?", "El làser aclareix la taca existent, però la pell pot tornar a pigmentar amb el sol. Amb una bona protecció solar el resultat es manté millor."),
                ("Quan veuré resultats?", "Després de cada sessió la taca s'enfosqueix lleugerament i després s'aclareix els dies següents; la millora és progressiva."),
                ("És dolorós?", "Es percep una molèstia breu i tolerable, gairebé sense temps de recuperació."),
                ("Quant costa?", "El preu depèn del nombre i tipus de taques, per això l'indiquem després de valorar la teva pell al nostre centre de Barcelona."),
            ],
        },
        "ru": {
            "name": "Осветление пигментации",
            "tag": "Солнечные и возрастные пятна — ровный тон",
            "intro": [
                "Работаем с солнечными пятнами, лентиго и другой гиперпигментацией селективным лазером: он действует на избыток меланина, не повреждая здоровую кожу.",
                "Результат — более ровный и сияющий тон. Протокол подбираем по типу и глубине пятен.",
            ],
            "benefits": ["Уменьшает солнечные и возрастные пятна", "Более ровный тон", "Действует на избыток меланина", "Протокол под ваш тип кожи"],
            "steps": [("Консультация", "Определяем тип пятен и ваш фототип."), ("Сеансы лазера", "Лазер направляет энергию на пигмент."), ("Результат", "Пятно постепенно светлеет.")],
            "tech": ["Q-Switched", "Er:YAG"],
            "faq": [
                ("Сколько нужно сеансов?", "Зависит от типа, количества и глубины пятен и от фототипа. Обычно предлагается план из нескольких сеансов, который определяем на консультации."),
                ("Пятна вернутся?", "Лазер осветляет существующее пятно, но кожа может снова пигментировать на солнце. С хорошей защитой от солнца результат держится лучше."),
                ("Когда виден результат?", "После каждого сеанса пятно слегка темнеет, а затем светлеет в последующие дни; улучшение постепенное."),
                ("Это больно?", "Ощущается краткий терпимый дискомфорт, почти без периода восстановления."),
                ("Сколько это стоит?", "Цена зависит от числа и типа пятен, поэтому называем её после осмотра кожи в нашем центре в Барселоне."),
            ],
        },
        "en": {
            "name": "Pigmentation lightening",
            "tag": "Sun and age spots for an even skin tone",
            "intro": [
                "We treat sun spots, lentigines and other hyperpigmentation with a selective laser that targets excess melanin without harming healthy skin.",
                "The result is a more even, radiant tone. We design the protocol according to the type and depth of the spots.",
            ],
            "benefits": ["Reduces sun and age spots", "More even skin tone", "Targets excess melanin", "Protocol for your skin type"],
            "steps": [("Assessment", "We identify the spot type and your skin phototype."), ("Laser sessions", "The laser directs its energy to the pigment."), ("Result", "The spot lightens progressively.")],
            "tech": ["Q-Switched", "Er:YAG"],
            "faq": [
                ("How many sessions do I need?", "It depends on the type, number and depth of the spots and your phototype. A plan of several sessions is usually proposed and defined at the assessment."),
                ("Will the spots come back?", "The laser lightens the existing spot, but skin can pigment again with sun exposure. With good sun protection the result lasts better."),
                ("When will I see results?", "After each session the spot darkens slightly and then lightens over the following days; the improvement is progressive."),
                ("Is it painful?", "A brief, tolerable sensation is felt, with barely any downtime."),
                ("How much does it cost?", "The price depends on the number and type of spots, so we give it after assessing your skin at our Barcelona clinic."),
            ],
        },
    },
    {
        "slug": "depilacion-laser",
        "img": "/assets/svc-depilacion-laser.jpg",
        "img2": "/assets/depil-2.jpg",
        "es": {
            "name": "Depilación láser",
            "tag": "Reducción del vello duradera, cómoda y segura",
            "intro": [
                "La depilación láser reduce el vello de forma progresiva y duradera, actuando sobre el folículo en su fase de crecimiento con total seguridad.",
                "Es apta para distintas zonas del cuerpo y tipos de piel. Planificamos las sesiones según tu ciclo de vello.",
            ],
            "benefits": ["Reducción duradera del vello", "Cómoda y segura", "Apta para distintas zonas", "Piel más suave y sin irritación"],
            "steps": [("Valoración", "Analizamos la zona, el vello y tu piel."), ("Sesiones", "El láser actúa sobre el folículo activo."), ("Mantenimiento", "Sesiones espaciadas para consolidar el resultado.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("¿Cuántas sesiones necesito?", "Depende de la zona, el color y el grosor del vello, el fototipo y factores hormonales. Suelen hacer falta varias sesiones espaciadas más algún mantenimiento; lo concretamos en la valoración."),
                ("¿Es segura en piel morena o bronceada?", "Con el láser Nd:YAG adaptamos el tratamiento a distintos fototipos. Aun así conviene evitar el bronceado los días previos."),
                ("¿Duele?", "Se percibe una molestia breve y tolerable. El equipo cuida tu comodidad durante toda la sesión."),
                ("¿Cómo preparo la piel?", "No te depiles con cera ni pinzas (el láser necesita la raíz), rasura la zona y evita el sol y el autobronceador los días previos."),
                ("¿Cuánto cuesta?", "El precio depende de las zonas a tratar, por eso lo indicamos tras la valoración en nuestro centro de Barcelona."),
            ],
        },
        "ca": {
            "name": "Depilació làser",
            "tag": "Reducció del pèl duradora, còmoda i segura",
            "intro": [
                "La depilació làser redueix el pèl de manera progressiva i duradora, actuant sobre el fol·licle en la seva fase de creixement amb total seguretat.",
                "És apta per a diferents zones del cos i tipus de pell. Planifiquem les sessions segons el teu cicle de pèl.",
            ],
            "benefits": ["Reducció duradora del pèl", "Còmoda i segura", "Apta per a diferents zones", "Pell més suau i sense irritació"],
            "steps": [("Valoració", "Analitzem la zona, el pèl i la teva pell."), ("Sessions", "El làser actua sobre el fol·licle actiu."), ("Manteniment", "Sessions espaiades per consolidar el resultat.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("Quantes sessions necessito?", "Depèn de la zona, el color i el gruix del pèl, el fototip i factors hormonals. Solen caldre diverses sessions espaiades més algun manteniment; ho concretem a la valoració."),
                ("És segura en pell morena o bronzejada?", "Amb el làser Nd:YAG adaptem el tractament a diferents fototips. Tot i així convé evitar el bronzejat els dies previs."),
                ("Fa mal?", "Es percep una molèstia breu i tolerable. L'equip té cura de la teva comoditat durant tota la sessió."),
                ("Com preparo la pell?", "No et depilis amb cera ni pinces (el làser necessita l'arrel), afaita la zona i evita el sol i l'autobronzejador els dies previs."),
                ("Quant costa?", "El preu depèn de les zones a tractar, per això l'indiquem després de la valoració al nostre centre de Barcelona."),
            ],
        },
        "ru": {
            "name": "Лазерная депиляция",
            "tag": "Долговременное, комфортное и безопасное удаление волос",
            "intro": [
                "Лазерная депиляция постепенно и надолго сокращает рост волос, воздействуя на фолликул в фазе роста — полностью безопасно.",
                "Подходит для разных зон тела и типов кожи. Сеансы планируем под ваш цикл роста волос.",
            ],
            "benefits": ["Долговременное сокращение волос", "Комфортно и безопасно", "Разные зоны тела", "Гладкая кожа без раздражения"],
            "steps": [("Консультация", "Анализируем зону, волосы и кожу."), ("Сеансы", "Лазер работает по активному фолликулу."), ("Поддержание", "Сеансы с интервалом закрепляют результат.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("Сколько нужно сеансов?", "Зависит от зоны, цвета и толщины волос, фототипа и гормональных факторов. Обычно нужно несколько сеансов с интервалом плюс поддержание; уточняем на консультации."),
                ("Безопасно ли для смуглой или загорелой кожи?", "С лазером Nd:YAG мы адаптируем процедуру под разные фототипы. Всё же лучше не загорать за несколько дней до сеанса."),
                ("Больно ли?", "Ощущается краткий терпимый дискомфорт. Команда заботится о вашем комфорте на протяжении всего сеанса."),
                ("Как подготовить кожу?", "Не удаляйте волосы воском и пинцетом (лазеру нужен корень), брейте зону и избегайте солнца и автозагара за несколько дней."),
                ("Сколько это стоит?", "Цена зависит от обрабатываемых зон, поэтому называем её после консультации в нашем центре в Барселоне."),
            ],
        },
        "en": {
            "name": "Laser hair removal",
            "tag": "Long-lasting, comfortable and safe hair reduction",
            "intro": [
                "Laser hair removal reduces hair progressively and durably, acting on the follicle during its growth phase with full safety.",
                "It is suitable for various body areas and skin types. We plan sessions around your hair cycle.",
            ],
            "benefits": ["Long-lasting hair reduction", "Comfortable and safe", "Suitable for various areas", "Smoother skin without irritation"],
            "steps": [("Assessment", "We analyse the area, the hair and your skin."), ("Sessions", "The laser acts on the active follicle."), ("Maintenance", "Spaced sessions consolidate the result.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("How many sessions do I need?", "It depends on the area, hair colour and thickness, phototype and hormonal factors. Several spaced sessions plus some maintenance are usually needed; we confirm this at the assessment."),
                ("Is it safe on darker or tanned skin?", "With the Nd:YAG laser we adapt the treatment to different phototypes. Even so, it's best to avoid tanning in the days before."),
                ("Does it hurt?", "A brief, tolerable sensation is felt. The team keeps you comfortable throughout the session."),
                ("How do I prepare my skin?", "Don't wax or pluck (the laser needs the root), shave the area and avoid sun and self-tanner in the days before."),
                ("How much does it cost?", "The price depends on the areas to be treated, so we give it after the assessment at our Barcelona clinic."),
            ],
        },
    },
    {
        "slug": "tratamiento-del-acne",
        "img": "/assets/svc-tratamiento-del-acne.jpg",
        "img2": "/assets/svc2-depilacion-laser.jpg",
        "es": {
            "name": "Tratamiento del acné",
            "tag": "Reduce la actividad sebácea y las marcas del acné",
            "intro": [
                "El láser ayuda a controlar el acné activo reduciendo la actividad de las glándulas sebáceas y la carga bacteriana, y mejora las marcas y cicatrices que deja.",
                "Combinamos protocolos según el tipo de acné y el estado de tu piel para un resultado equilibrado.",
            ],
            "benefits": ["Reduce el acné activo", "Mejora marcas y cicatrices", "Menos brillo y poro más fino", "Protocolo según tu piel"],
            "steps": [("Valoración", "Evaluamos el tipo de acné y tu piel."), ("Sesiones láser", "Actuamos sobre la glándula y las marcas."), ("Resultado", "Piel más equilibrada y uniforme.")],
            "tech": ["Nd:YAG", "Láser Fraccional"],
            "faq": [
                ("¿Sirve para el acné activo y para las marcas?", "Sí. El láser ayuda a controlar el acné activo y, en otro enfoque, mejora las marcas y cicatrices que deja. Adaptamos el protocolo a cada objetivo."),
                ("¿Cuántas sesiones necesito?", "Depende del tipo de acné y del estado de tu piel. Se plantea un plan de varias sesiones que definimos en la valoración."),
                ("¿Cuándo veré resultados?", "La piel mejora de forma progresiva a lo largo de las sesiones; en el acné activo suele notarse menos brillo y menos brotes."),
                ("¿Tiene tiempo de baja?", "Es un tratamiento cómodo con poco o ningún tiempo de recuperación, según el protocolo."),
                ("¿Se combina con otros cuidados?", "Sí, podemos integrarlo en una rutina dermatológica. Te orientamos en la valoración en nuestro centro de Barcelona."),
            ],
        },
        "ca": {
            "name": "Tractament de l'acne",
            "tag": "Redueix l'activitat sebàcia i les marques de l'acne",
            "intro": [
                "El làser ajuda a controlar l'acne actiu reduint l'activitat de les glàndules sebàcies i la càrrega bacteriana, i millora les marques i cicatrius que deixa.",
                "Combinem protocols segons el tipus d'acne i l'estat de la teva pell per a un resultat equilibrat.",
            ],
            "benefits": ["Redueix l'acne actiu", "Millora marques i cicatrius", "Menys brillantor i porus més fi", "Protocol segons la teva pell"],
            "steps": [("Valoració", "Avaluem el tipus d'acne i la teva pell."), ("Sessions làser", "Actuem sobre la glàndula i les marques."), ("Resultat", "Pell més equilibrada i uniforme.")],
            "tech": ["Nd:YAG", "Làser Fraccional"],
            "faq": [
                ("Serveix per a l'acne actiu i per a les marques?", "Sí. El làser ajuda a controlar l'acne actiu i, en un altre enfocament, millora les marques i cicatrius que deixa. Adaptem el protocol a cada objectiu."),
                ("Quantes sessions necessito?", "Depèn del tipus d'acne i de l'estat de la teva pell. Es planteja un pla de diverses sessions que definim a la valoració."),
                ("Quan veuré resultats?", "La pell millora de manera progressiva al llarg de les sessions; en l'acne actiu se sol notar menys brillantor i menys brots."),
                ("Té temps de baixa?", "És un tractament còmode amb poc o cap temps de recuperació, segons el protocol."),
                ("Es combina amb altres cures?", "Sí, podem integrar-ho en una rutina dermatològica. T'orientem a la valoració al nostre centre de Barcelona."),
            ],
        },
        "ru": {
            "name": "Лечение акне",
            "tag": "Снижает активность сальных желёз и следы акне",
            "intro": [
                "Лазер помогает контролировать активное акне, снижая активность сальных желёз и бактериальную нагрузку, а также улучшает следы и рубцы.",
                "Комбинируем протоколы по типу акне и состоянию кожи для сбалансированного результата.",
            ],
            "benefits": ["Уменьшает активное акне", "Улучшает следы и рубцы", "Меньше жирного блеска, уже поры", "Протокол под вашу кожу"],
            "steps": [("Консультация", "Оцениваем тип акне и кожу."), ("Сеансы лазера", "Работаем по железе и следам."), ("Результат", "Более ровная, сбалансированная кожа.")],
            "tech": ["Nd:YAG", "Фракционный лазер"],
            "faq": [
                ("Помогает при активном акне и при следах?", "Да. Лазер помогает контролировать активное акне, а в другом подходе улучшает следы и рубцы. Протокол адаптируем под каждую задачу."),
                ("Сколько нужно сеансов?", "Зависит от типа акне и состояния кожи. Предлагается план из нескольких сеансов, который определяем на консультации."),
                ("Когда виден результат?", "Кожа улучшается постепенно в ходе сеансов; при активном акне обычно уменьшается жирный блеск и число высыпаний."),
                ("Есть период восстановления?", "Процедура комфортная, с небольшим периодом восстановления или без него — в зависимости от протокола."),
                ("Сочетается с другим уходом?", "Да, можем встроить в дерматологическую рутину. Сориентируем на консультации в нашем центре в Барселоне."),
            ],
        },
        "en": {
            "name": "Acne treatment",
            "tag": "Reduces sebaceous activity and acne marks",
            "intro": [
                "The laser helps control active acne by reducing sebaceous gland activity and bacterial load, and improves the marks and scars it leaves behind.",
                "We combine protocols according to the acne type and your skin condition for a balanced result.",
            ],
            "benefits": ["Reduces active acne", "Improves marks and scars", "Less shine, refined pores", "Protocol for your skin"],
            "steps": [("Assessment", "We evaluate the acne type and your skin."), ("Laser sessions", "We act on the gland and the marks."), ("Result", "More balanced, even skin.")],
            "tech": ["Nd:YAG", "Fractional laser"],
            "faq": [
                ("Does it work for active acne and for marks?", "Yes. The laser helps control active acne and, in a different approach, improves the marks and scars it leaves. We adapt the protocol to each goal."),
                ("How many sessions do I need?", "It depends on the acne type and your skin condition. A plan of several sessions is proposed and defined at the assessment."),
                ("When will I see results?", "The skin improves progressively over the sessions; with active acne there is usually less shine and fewer breakouts."),
                ("Is there downtime?", "It is a comfortable treatment with little or no recovery time, depending on the protocol."),
                ("Can it be combined with other care?", "Yes, we can integrate it into a dermatological routine. We guide you at the assessment at our Barcelona clinic."),
            ],
        },
    },
    {
        "slug": "aranas-vasculares-rosacea",
        "img": "/assets/svc-aranas-vasculares-rosacea.jpg",
        "img2": "/assets/clinic-facial.jpg",
        "es": {
            "name": "Arañas vasculares y rosácea",
            "tag": "Cierra capilares dilatados y reduce el enrojecimiento",
            "intro": [
                "El láser vascular actúa de forma selectiva sobre los capilares dilatados y el enrojecimiento de la rosácea, cerrando los vasos sin afectar a la piel sana.",
                "Es un tratamiento preciso que mejora visiblemente el aspecto de la piel reactiva y las arañas vasculares.",
            ],
            "benefits": ["Reduce arañas vasculares", "Menos enrojecimiento y rojeces", "Acción selectiva sobre el vaso", "Piel de aspecto más calmado"],
            "steps": [("Valoración", "Analizamos los vasos y tu tipo de piel."), ("Sesiones láser", "El láser cierra los capilares tratados."), ("Resultado", "El enrojecimiento se atenúa progresivamente.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("¿Cuántas sesiones necesito?", "Depende de la extensión y del tipo de vasos o rojeces. Se plantea un plan de varias sesiones que estimamos en la valoración."),
                ("¿Es doloroso?", "Se percibe una molestia breve y tolerable, similar a un pequeño chasquido de calor, sin apenas tiempo de recuperación."),
                ("¿Cuándo veré resultados?", "El enrojecimiento y los vasos tratados se atenúan de forma progresiva en las semanas siguientes a cada sesión."),
                ("¿El láser cura la rosácea?", "La rosácea es crónica y no tiene cura definitiva; el láser ayuda a reducir las rojeces y los vasos visibles y a mantener la piel más calmada."),
                ("¿Cuánto cuesta?", "El precio depende de la zona y del número de sesiones, por eso lo indicamos tras valorar tu piel en nuestro centro de Barcelona."),
            ],
        },
        "ca": {
            "name": "Aranyes vasculars i rosàcia",
            "tag": "Tanca capil·lars dilatats i redueix l'envermelliment",
            "intro": [
                "El làser vascular actua de manera selectiva sobre els capil·lars dilatats i l'envermelliment de la rosàcia, tancant els vasos sense afectar la pell sana.",
                "És un tractament precís que millora visiblement l'aspecte de la pell reactiva i les aranyes vasculars.",
            ],
            "benefits": ["Redueix aranyes vasculars", "Menys envermelliment i rojors", "Acció selectiva sobre el vas", "Pell d'aspecte més calmat"],
            "steps": [("Valoració", "Analitzem els vasos i el teu tipus de pell."), ("Sessions làser", "El làser tanca els capil·lars tractats."), ("Resultat", "L'envermelliment s'atenua progressivament.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("Quantes sessions necessito?", "Depèn de l'extensió i del tipus de vasos o rojors. Es planteja un pla de diverses sessions que estimem a la valoració."),
                ("És dolorós?", "Es percep una molèstia breu i tolerable, semblant a un petit espetec de calor, gairebé sense temps de recuperació."),
                ("Quan veuré resultats?", "L'envermelliment i els vasos tractats s'atenuen de manera progressiva les setmanes següents a cada sessió."),
                ("El làser cura la rosàcia?", "La rosàcia és crònica i no té cura definitiva; el làser ajuda a reduir les rojors i els vasos visibles i a mantenir la pell més calmada."),
                ("Quant costa?", "El preu depèn de la zona i del nombre de sessions, per això l'indiquem després de valorar la teva pell al nostre centre de Barcelona."),
            ],
        },
        "ru": {
            "name": "Сосудистые звёздочки и розацеа",
            "tag": "Закрывает расширенные капилляры, убирает покраснение",
            "intro": [
                "Сосудистый лазер избирательно действует на расширенные капилляры и покраснение при розацеа, закрывая сосуды без вреда для здоровой кожи.",
                "Это точная процедура, которая заметно улучшает вид реактивной кожи и сосудистых звёздочек.",
            ],
            "benefits": ["Убирает сосудистые звёздочки", "Меньше покраснений", "Избирательно по сосуду", "Более спокойный вид кожи"],
            "steps": [("Консультация", "Анализируем сосуды и тип кожи."), ("Сеансы лазера", "Лазер закрывает обработанные капилляры."), ("Результат", "Покраснение постепенно уходит.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("Сколько нужно сеансов?", "Зависит от площади и типа сосудов или покраснений. Предлагается план из нескольких сеансов, который оцениваем на консультации."),
                ("Это больно?", "Ощущается краткий терпимый дискомфорт, похожий на лёгкий тепловой щелчок, почти без периода восстановления."),
                ("Когда виден результат?", "Покраснение и обработанные сосуды постепенно бледнеют в недели после каждого сеанса."),
                ("Лазер лечит розацеа?", "Розацеа хроническая и не имеет полного излечения; лазер помогает уменьшить покраснения и видимые сосуды и сохранять кожу более спокойной."),
                ("Сколько это стоит?", "Цена зависит от зоны и числа сеансов, поэтому называем её после осмотра кожи в нашем центре в Барселоне."),
            ],
        },
        "en": {
            "name": "Spider veins & rosacea",
            "tag": "Closes dilated capillaries and reduces redness",
            "intro": [
                "The vascular laser acts selectively on dilated capillaries and rosacea redness, closing the vessels without affecting healthy skin.",
                "It is a precise treatment that visibly improves the appearance of reactive skin and spider veins.",
            ],
            "benefits": ["Reduces spider veins", "Less redness and flushing", "Selective vessel action", "Calmer-looking skin"],
            "steps": [("Assessment", "We analyse the vessels and your skin type."), ("Laser sessions", "The laser closes the treated capillaries."), ("Result", "Redness fades progressively.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("How many sessions do I need?", "It depends on the extent and type of vessels or redness. A plan of several sessions is proposed and estimated at the assessment."),
                ("Is it painful?", "A brief, tolerable sensation is felt, like a small snap of heat, with barely any downtime."),
                ("When will I see results?", "Redness and treated vessels fade progressively in the weeks after each session."),
                ("Does the laser cure rosacea?", "Rosacea is chronic and has no definitive cure; the laser helps reduce redness and visible vessels and keep the skin calmer."),
                ("How much does it cost?", "The price depends on the area and number of sessions, so we give it after assessing your skin at our Barcelona clinic."),
            ],
        },
    },
    {
        "slug": "cicatrices-y-estrias",
        "img": "/assets/svc-cicatrices-y-estrias.jpg",
        "img2": "/assets/fotona-device.jpg",
        "es": {
            "name": "Cicatrices y estrías",
            "tag": "Láser fraccional que mejora textura y suaviza marcas",
            "intro": [
                "El láser fraccional renueva la piel por microzonas, estimulando el colágeno para mejorar la textura y suavizar cicatrices y estrías.",
                "Es eficaz en cicatrices de acné, quirúrgicas y estrías, con un enfoque progresivo y personalizado.",
            ],
            "benefits": ["Suaviza cicatrices y estrías", "Mejora la textura de la piel", "Estimula colágeno nuevo", "Resultados progresivos"],
            "steps": [("Valoración", "Estudiamos la cicatriz o estría y tu piel."), ("Sesiones", "El láser fraccional renueva la zona."), ("Resultado", "La textura mejora de forma progresiva.")],
            "tech": ["Láser Fraccional", "Er:YAG"],
            "faq": [
                ("¿Funciona en cicatrices y estrías antiguas?", "Mejora la textura y el color tanto en marcas recientes como antiguas, aunque el resultado varía según la zona y el tipo de marca. Lo valoramos caso a caso."),
                ("¿Cuántas sesiones necesito?", "Depende de la zona, la profundidad y el tipo de cicatriz o estría. Se plantea un plan de varias sesiones que definimos en la valoración."),
                ("¿Cuándo veré resultados?", "La textura mejora de forma progresiva en las semanas y meses posteriores, a medida que se genera colágeno nuevo."),
                ("¿Es doloroso? ¿Tiene tiempo de baja?", "Se percibe una molestia tolerable; puede haber un ligero enrojecimiento unos días según la intensidad del protocolo."),
                ("¿Cuánto cuesta?", "El precio depende de la zona y del número de sesiones, por eso lo indicamos tras la valoración en nuestro centro de Barcelona."),
            ],
        },
        "ca": {
            "name": "Cicatrius i estries",
            "tag": "Làser fraccional que millora la textura i suavitza les marques",
            "intro": [
                "El làser fraccional renova la pell per microzones, estimulant el col·lagen per millorar la textura i suavitzar cicatrius i estries.",
                "És eficaç en cicatrius d'acne, quirúrgiques i estries, amb un enfocament progressiu i personalitzat.",
            ],
            "benefits": ["Suavitza cicatrius i estries", "Millora la textura de la pell", "Estimula col·lagen nou", "Resultats progressius"],
            "steps": [("Valoració", "Estudiem la cicatriu o estria i la teva pell."), ("Sessions", "El làser fraccional renova la zona."), ("Resultat", "La textura millora de manera progressiva.")],
            "tech": ["Làser Fraccional", "Er:YAG"],
            "faq": [
                ("Funciona en cicatrius i estries antigues?", "Millora la textura i el color tant en marques recents com antigues, tot i que el resultat varia segons la zona i el tipus de marca. Ho valorem cas a cas."),
                ("Quantes sessions necessito?", "Depèn de la zona, la profunditat i el tipus de cicatriu o estria. Es planteja un pla de diverses sessions que definim a la valoració."),
                ("Quan veuré resultats?", "La textura millora de manera progressiva les setmanes i mesos posteriors, a mesura que es genera col·lagen nou."),
                ("És dolorós? Té temps de baixa?", "Es percep una molèstia tolerable; pot haver-hi un lleuger envermelliment uns dies segons la intensitat del protocol."),
                ("Quant costa?", "El preu depèn de la zona i del nombre de sessions, per això l'indiquem després de la valoració al nostre centre de Barcelona."),
            ],
        },
        "ru": {
            "name": "Рубцы и растяжки",
            "tag": "Фракционный лазер улучшает текстуру и сглаживает следы",
            "intro": [
                "Фракционный лазер обновляет кожу микрозонами, стимулируя коллаген, чтобы улучшить текстуру и сгладить рубцы и растяжки.",
                "Эффективен при рубцах постакне, послеоперационных и растяжках — постепенный, индивидуальный подход.",
            ],
            "benefits": ["Сглаживает рубцы и растяжки", "Улучшает текстуру кожи", "Стимулирует новый коллаген", "Постепенный результат"],
            "steps": [("Консультация", "Изучаем рубец/растяжку и кожу."), ("Сеансы", "Фракционный лазер обновляет зону."), ("Результат", "Текстура улучшается постепенно.")],
            "tech": ["Фракционный лазер", "Er:YAG"],
            "faq": [
                ("Работает на старых рубцах и растяжках?", "Улучшает текстуру и цвет как на свежих, так и на старых следах, хотя результат зависит от зоны и типа следа. Оцениваем индивидуально."),
                ("Сколько нужно сеансов?", "Зависит от зоны, глубины и типа рубца или растяжки. Предлагается план из нескольких сеансов, который определяем на консультации."),
                ("Когда виден результат?", "Текстура улучшается постепенно в последующие недели и месяцы, по мере выработки нового коллагена."),
                ("Это больно? Есть период восстановления?", "Ощущается терпимый дискомфорт; возможно лёгкое покраснение на несколько дней в зависимости от интенсивности протокола."),
                ("Сколько это стоит?", "Цена зависит от зоны и числа сеансов, поэтому называем её после консультации в нашем центре в Барселоне."),
            ],
        },
        "en": {
            "name": "Scars & stretch marks",
            "tag": "Fractional laser that improves texture and softens marks",
            "intro": [
                "The fractional laser renews the skin in micro-zones, stimulating collagen to improve texture and soften scars and stretch marks.",
                "It is effective on acne, surgical scars and stretch marks, with a progressive, personalised approach.",
            ],
            "benefits": ["Softens scars and stretch marks", "Improves skin texture", "Stimulates new collagen", "Progressive results"],
            "steps": [("Assessment", "We study the scar or stretch mark and your skin."), ("Sessions", "The fractional laser renews the area."), ("Result", "Texture improves progressively.")],
            "tech": ["Fractional laser", "Er:YAG"],
            "faq": [
                ("Does it work on old scars and stretch marks?", "It improves texture and colour on both recent and old marks, though the result varies with the area and type of mark. We assess each case individually."),
                ("How many sessions do I need?", "It depends on the area, depth and type of scar or stretch mark. A plan of several sessions is proposed and defined at the assessment."),
                ("When will I see results?", "Texture improves progressively over the following weeks and months, as new collagen forms."),
                ("Is it painful? Is there downtime?", "A tolerable sensation is felt; there may be slight redness for a few days depending on the intensity of the protocol."),
                ("How much does it cost?", "The price depends on the area and number of sessions, so we give it after the assessment at our Barcelona clinic."),
            ],
        },
    },
    {
        "slug": "onicomicosis",
        "img": "/assets/svc-onicomicosis.jpg",
        "img2": "/assets/svc2-cicatrices-y-estrias.jpg",
        "es": {
            "name": "Onicomicosis (hongos)",
            "tag": "Tratamiento láser de los hongos de las uñas",
            "intro": [
                "El láser trata la onicomicosis (hongos de las uñas) actuando por calor sobre el hongo alojado en la uña y el lecho ungueal, sin necesidad de fármacos orales prolongados ni de sus controles analíticos.",
                "Es una opción cómoda y prácticamente sin tiempo de recuperación: tras la sesión puedes retomar tu día con normalidad. El número de sesiones depende del número de uñas afectadas y del grado de afectación.",
                "En nuestra clínica de Barcelona valoramos primero el estado de la uña y, cuando procede, combinamos el tratamiento con pautas de higiene y cuidado del calzado para reducir el riesgo de recidiva. Los resultados se aprecian de forma progresiva, a medida que crece la uña sana.",
            ],
            "benefits": ["Actúa por calor sobre el hongo de la uña", "Sin fármacos orales prolongados ni analíticas", "Prácticamente sin tiempo de recuperación", "Permite tratar varias uñas en una misma sesión", "Protocolo según el grado de afectación"],
            "steps": [("Valoración", "Examinamos la uña y el grado de afectación y definimos el número de sesiones."), ("Sesiones láser", "El calor del láser Nd:YAG actúa sobre el hongo en la uña y el lecho ungueal."), ("Seguimiento", "Revisamos el crecimiento de la uña sana y reforzamos las pautas de higiene.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("¿Cuántas sesiones necesito?", "Depende del número de uñas afectadas y del grado de afectación. Suelen precisarse varias sesiones espaciadas; el plan concreto se define en la valoración inicial."),
                ("¿El láser elimina el hongo de la uña?", "El láser actúa por calor reduciendo la carga del hongo; la uña dañada no se «cura» de golpe, sino que se sustituye a medida que crece una uña nueva y sana. Los resultados varían según cada caso, por eso trabajamos con una valoración individualizada."),
                ("¿Cuánto tarda en verse el resultado?", "La uña crece despacio, así que la mejora se aprecia de forma progresiva a lo largo de los meses siguientes, según va saliendo uña sana desde la base."),
                ("¿Es doloroso?", "Se percibe un calor tolerable durante la sesión. No requiere anestesia y puedes retomar tu actividad normal el mismo día."),
                ("¿Cuánto cuesta?", "El precio se ajusta al número de uñas y al grado de afectación, por eso lo indicamos tras valorar la uña. Así te damos una cifra honesta y no una estimación al azar."),
                ("¿Cómo evito que vuelva a aparecer?", "Ayuda mantener una buena higiene, secar bien los pies, usar calzado transpirable y desinfectar calzado y calcetines. En la consulta te damos pautas para reducir el riesgo de recaída."),
            ],
        },
        "ca": {
            "name": "Onicomicosi (fongs)",
            "tag": "Tractament làser dels fongs de les ungles",
            "intro": [
                "El làser tracta l'onicomicosi (fongs de les ungles) actuant per calor sobre el fong allotjat a l'ungla i el llit ungueal, sense necessitat de fàrmacs orals prolongats ni dels seus controls analítics.",
                "És una opció còmoda i pràcticament sense temps de recuperació: després de la sessió pots reprendre el teu dia amb normalitat. El nombre de sessions depèn del nombre d'ungles afectades i del grau d'afectació.",
                "A la nostra clínica de Barcelona valorem primer l'estat de l'ungla i, quan escau, combinem el tractament amb pautes d'higiene i cura del calçat per reduir el risc de recidiva. Els resultats s'aprecien de manera progressiva, a mesura que creix l'ungla sana.",
            ],
            "benefits": ["Actua per calor sobre el fong de l'ungla", "Sense fàrmacs orals prolongats ni analítiques", "Pràcticament sense temps de recuperació", "Permet tractar diverses ungles en una mateixa sessió", "Protocol segons el grau d'afectació"],
            "steps": [("Valoració", "Examinem l'ungla i el grau d'afectació i definim el nombre de sessions."), ("Sessions làser", "La calor del làser Nd:YAG actua sobre el fong a l'ungla i el llit ungueal."), ("Seguiment", "Revisem el creixement de l'ungla sana i reforcem les pautes d'higiene.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("Quantes sessions necessito?", "Depèn del nombre d'ungles afectades i del grau d'afectació. Solen caldre diverses sessions espaiades; el pla concret es defineix a la valoració inicial."),
                ("El làser elimina el fong de l'ungla?", "El làser actua per calor reduint la càrrega del fong; l'ungla malmesa no es «cura» de cop, sinó que se substitueix a mesura que creix una ungla nova i sana. Els resultats varien segons cada cas, per això treballem amb una valoració individualitzada."),
                ("Quant triga a veure's el resultat?", "L'ungla creix a poc a poc, així que la millora s'aprecia de manera progressiva al llarg dels mesos següents, a mesura que surt ungla sana des de la base."),
                ("És dolorós?", "Es percep una calor tolerable durant la sessió. No requereix anestèsia i pots reprendre la teva activitat normal el mateix dia."),
                ("Quant costa?", "El preu s'ajusta al nombre d'ungles i al grau d'afectació, per això l'indiquem després de valorar l'ungla. Així et donem una xifra honesta i no una estimació a l'atzar."),
                ("Com evito que torni a aparèixer?", "Ajuda mantenir una bona higiene, eixugar bé els peus, fer servir calçat transpirable i desinfectar calçat i mitjons. A la consulta et donem pautes per reduir el risc de recaiguda."),
            ],
        },
        "ru": {
            "name": "Онихомикоз (грибок ногтей)",
            "tag": "Лазерное лечение грибка ногтей",
            "intro": [
                "Лазер лечит онихомикоз (грибок ногтей), воздействуя теплом на грибок в ногтевой пластине и ложе, без длительного приёма таблеток и связанных с ним анализов.",
                "Это удобный вариант практически без периода восстановления: после сеанса можно вернуться к обычным делам. Число сеансов зависит от количества поражённых ногтей и степени поражения.",
                "В нашей клинике в Барселоне мы сначала оцениваем состояние ногтя и при необходимости дополняем процедуру рекомендациями по гигиене и уходу за обувью, чтобы снизить риск рецидива. Результат проявляется постепенно, по мере отрастания здорового ногтя.",
            ],
            "benefits": ["Действует теплом на грибок ногтя", "Без долгих таблеток и анализов", "Практически без периода восстановления", "Можно обработать несколько ногтей за сеанс", "Протокол по степени поражения"],
            "steps": [("Консультация", "Осматриваем ноготь и степень поражения, определяем число сеансов."), ("Сеансы лазера", "Тепло лазера Nd:YAG действует на грибок в ногте и ложе."), ("Наблюдение", "Контролируем отрастание здорового ногтя и закрепляем гигиенические привычки.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("Сколько нужно сеансов?", "Зависит от числа поражённых ногтей и степени поражения. Обычно нужно несколько сеансов с интервалом; точный план определяем на первой консультации."),
                ("Лазер убирает грибок ногтя?", "Лазер теплом снижает нагрузку грибка; повреждённый ноготь не «излечивается» мгновенно — он сменяется по мере отрастания нового здорового ногтя. Результат индивидуален, поэтому мы работаем через очную оценку."),
                ("Когда виден результат?", "Ноготь растёт медленно, поэтому улучшение заметно постепенно в течение следующих месяцев, по мере того как здоровый ноготь отрастает от основания."),
                ("Это больно?", "Во время сеанса ощущается терпимое тепло. Анестезия не нужна, вернуться к обычным делам можно в тот же день."),
                ("Сколько это стоит?", "Цена зависит от числа ногтей и степени поражения, поэтому мы называем её после осмотра ногтя. Так мы даём честную цифру, а не наугад."),
                ("Как не допустить возвращения грибка?", "Помогают хорошая гигиена, тщательное просушивание стоп, дышащая обувь и дезинфекция обуви и носков. На консультации мы даём рекомендации, чтобы снизить риск рецидива."),
            ],
        },
        "en": {
            "name": "Onychomycosis (nail fungus)",
            "tag": "Laser treatment for nail fungus",
            "intro": [
                "The laser treats onychomycosis (nail fungus) by acting with heat on the fungus in the nail plate and nail bed, without the need for prolonged oral medication or its blood-test monitoring.",
                "It is a comfortable option with virtually no downtime: after the session you can carry on with your day. The number of sessions depends on how many nails are affected and how advanced they are.",
                "At our clinic in Barcelona we first assess the state of the nail and, where appropriate, combine the treatment with hygiene and footwear-care guidance to reduce the risk of recurrence. Results appear gradually, as the healthy nail grows out.",
            ],
            "benefits": ["Acts with heat on the nail fungus", "No prolonged oral medication or blood tests", "Virtually no downtime", "Several nails can be treated in one session", "Protocol based on severity"],
            "steps": [("Assessment", "We examine the nail and the severity and define the number of sessions."), ("Laser sessions", "The Nd:YAG laser heat acts on the fungus in the nail and nail bed."), ("Follow-up", "We review the healthy nail's growth and reinforce hygiene habits.")],
            "tech": ["Nd:YAG"],
            "faq": [
                ("How many sessions do I need?", "It depends on how many nails are affected and how advanced they are. Several spaced sessions are usually needed; the specific plan is set at the initial assessment."),
                ("Does the laser remove the nail fungus?", "The laser uses heat to reduce the fungal load; the damaged nail is not «cured» instantly — it is replaced as a new, healthy nail grows. Results vary from case to case, which is why we work with an individual assessment."),
                ("How long until I see results?", "Nails grow slowly, so the improvement shows gradually over the following months, as healthy nail grows from the base."),
                ("Is it painful?", "A tolerable warmth is felt during the session. No anaesthesia is needed and you can resume your normal activity the same day."),
                ("How much does it cost?", "The price depends on the number of nails and the severity, so we give it after assessing the nail. That way we give you an honest figure rather than a random estimate."),
                ("How do I stop it coming back?", "Good hygiene, drying your feet well, breathable footwear and disinfecting shoes and socks all help. At the consultation we give you guidance to lower the risk of recurrence."),
            ],
        },
    },
    {
        "slug": "rejuvenecimiento-4d-fotona",
        "img": "/assets/benefits.jpg",
        "external": "https://4dfotona.es/",  # sitio separado (como en el original)
        "badge": {"es": "Estrella", "ca": "Estrella", "ru": "Флагман", "en": "Signature"},
        "es": {
            "name": "Rejuvenecimiento 4D Fotona",
            "tag": "Efecto lifting sin cirugía, dentro y fuera de la piel",
            "intro": [
                "El protocolo Fotona 4D combina varios modos de láser para trabajar la piel desde el interior de la boca y desde el exterior, logrando un efecto tensor y de rejuvenecimiento global.",
                "Es un tratamiento no invasivo, sin cirugía ni tiempo de baja, que mejora firmeza, contorno y luminosidad.",
            ],
            "benefits": ["Efecto lifting sin cirugía", "Trabaja dentro y fuera de la piel", "Mejora firmeza y contorno", "Sin tiempo de baja"],
            "steps": [("Valoración", "Estudiamos tu rostro y objetivos."), ("Protocolo 4D", "Aplicamos los modos de láser Fotona."), ("Resultado", "Firmeza y luminosidad progresivas.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("¿Es una cirugía?", "No, es un tratamiento láser no invasivo."), ("¿Cuántas sesiones?", "Diseñamos el plan en la valoración inicial.")],
        },
        "ca": {
            "name": "Rejoveniment 4D Fotona",
            "tag": "Efecte lifting sense cirurgia, dins i fora de la pell",
            "intro": [
                "El protocol Fotona 4D combina diversos modes de làser per treballar la pell des de l'interior de la boca i des de l'exterior, aconseguint un efecte tensor i de rejoveniment global.",
                "És un tractament no invasiu, sense cirurgia ni temps de baixa, que millora fermesa, contorn i lluminositat.",
            ],
            "benefits": ["Efecte lifting sense cirurgia", "Treballa dins i fora de la pell", "Millora fermesa i contorn", "Sense temps de baixa"],
            "steps": [("Valoració", "Estudiem el teu rostre i objectius."), ("Protocol 4D", "Apliquem els modes de làser Fotona."), ("Resultat", "Fermesa i lluminositat progressives.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("És una cirurgia?", "No, és un tractament làser no invasiu."), ("Quantes sessions?", "Dissenyem el pla a la valoració inicial.")],
        },
        "ru": {
            "name": "Омоложение 4D Fotona",
            "tag": "Эффект лифтинга без хирургии — снаружи и изнутри",
            "intro": [
                "Протокол Fotona 4D сочетает несколько режимов лазера, работая с кожей изнутри полости рта и снаружи, создавая подтягивающий эффект и общее омоложение.",
                "Это неинвазивная процедура — без хирургии и простоя — улучшающая плотность, контур и сияние.",
            ],
            "benefits": ["Лифтинг без хирургии", "Работа снаружи и изнутри", "Плотность и контур", "Без простоя"],
            "steps": [("Консультация", "Изучаем лицо и цели."), ("Протокол 4D", "Применяем режимы лазера Fotona."), ("Результат", "Плотность и сияние нарастают.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Это операция?", "Нет, это неинвазивная лазерная процедура."), ("Сколько сеансов?", "План составим на первой консультации.")],
        },
        "en": {
            "name": "Fotona 4D rejuvenation",
            "tag": "Non-surgical lifting effect, inside and out",
            "intro": [
                "The Fotona 4D protocol combines several laser modes to work the skin both from inside the mouth and from the outside, achieving a tightening and overall rejuvenation effect.",
                "It is a non-invasive treatment, with no surgery or downtime, improving firmness, contour and radiance.",
            ],
            "benefits": ["Non-surgical lifting effect", "Works inside and outside the skin", "Improves firmness and contour", "No downtime"],
            "steps": [("Assessment", "We study your face and goals."), ("4D protocol", "We apply the Fotona laser modes."), ("Result", "Progressive firmness and radiance.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Is it surgery?", "No, it is a non-invasive laser treatment."), ("How many sessions?", "We design the plan at the initial assessment.")],
        },
    },
    {
        "slug": "eliminacion-de-neoplasias",
        "img": "/assets/proc-hand-1.jpg",
        "img2": "/assets/svc2-eliminacion-de-neoplasias.jpg",
        "es": {
            "name": "Eliminación de lesiones cutáneas",
            "tag": "Retirada precisa de lesiones benignas de la piel",
            "intro": [
                "Retiramos con láser lesiones cutáneas benignas —como verrugas, fibromas o pequeñas lesiones— de forma precisa y con buena cicatrización.",
                "Toda lesión se valora previamente; si procede, se deriva a estudio médico antes de cualquier actuación.",
            ],
            "benefits": ["Retirada precisa de la lesión", "Buena cicatrización", "Valoración médica previa", "Procedimiento cómodo"],
            "steps": [("Valoración", "Examinamos la lesión y decidimos el enfoque."), ("Procedimiento láser", "Retiramos la lesión con precisión."), ("Cuidado", "Pautas de cuidado para una cicatrización óptima.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [
                ("¿Qué lesiones se pueden tratar?", "Solo lesiones cutáneas benignas —como verrugas, fibromas o pequeñas lesiones— y siempre tras una valoración. Si hay cualquier duda sobre la lesión, se deriva a estudio médico antes de actuar."),
                ("¿Deja marca o cicatriz?", "Buscamos la mejor cicatrización posible; con los cuidados adecuados la marca suele ser mínima, aunque el resultado varía según la lesión y la piel."),
                ("¿Es doloroso?", "Es un procedimiento cómodo; según la lesión puede aplicarse anestesia local. Te lo explicamos en la valoración."),
                ("¿Cuántas sesiones necesito?", "Muchas lesiones se retiran en una sola sesión; otras requieren revisión o una sesión adicional. Lo definimos al valorar la lesión."),
                ("¿Cuánto cuesta?", "El precio depende del tipo y número de lesiones, por eso lo indicamos tras valorarlas en nuestro centro de Barcelona."),
            ],
        },
        "ca": {
            "name": "Eliminació de lesions cutànies",
            "tag": "Retirada precisa de lesions benignes de la pell",
            "intro": [
                "Retirem amb làser lesions cutànies benignes —com berrugues, fibromes o petites lesions— de manera precisa i amb bona cicatrització.",
                "Tota lesió es valora prèviament; si escau, es deriva a estudi mèdic abans de qualsevol actuació.",
            ],
            "benefits": ["Retirada precisa de la lesió", "Bona cicatrització", "Valoració mèdica prèvia", "Procediment còmode"],
            "steps": [("Valoració", "Examinem la lesió i decidim l'enfocament."), ("Procediment làser", "Retirem la lesió amb precisió."), ("Cura", "Pautes de cura per a una cicatrització òptima.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [
                ("Quines lesions es poden tractar?", "Només lesions cutànies benignes —com berrugues, fibromes o petites lesions— i sempre després d'una valoració. Si hi ha qualsevol dubte sobre la lesió, es deriva a estudi mèdic abans d'actuar."),
                ("Deixa marca o cicatriu?", "Busquem la millor cicatrització possible; amb les cures adequades la marca sol ser mínima, tot i que el resultat varia segons la lesió i la pell."),
                ("És dolorós?", "És un procediment còmode; segons la lesió es pot aplicar anestèsia local. T'ho expliquem a la valoració."),
                ("Quantes sessions necessito?", "Moltes lesions es retiren en una sola sessió; altres requereixen revisió o una sessió addicional. Ho definim en valorar la lesió."),
                ("Quant costa?", "El preu depèn del tipus i nombre de lesions, per això l'indiquem després de valorar-les al nostre centre de Barcelona."),
            ],
        },
        "ru": {
            "name": "Удаление кожных образований",
            "tag": "Точное удаление доброкачественных образований кожи",
            "intro": [
                "Удаляем лазером доброкачественные образования кожи — бородавки, фибромы, небольшие элементы — точно и с хорошим заживлением.",
                "Каждое образование сначала оценивается; при необходимости направляем на медицинское обследование до любых действий.",
            ],
            "benefits": ["Точное удаление образования", "Хорошее заживление", "Предварительная оценка врача", "Комфортная процедура"],
            "steps": [("Консультация", "Осматриваем образование и выбираем подход."), ("Лазерная процедура", "Удаляем элемент с точностью."), ("Уход", "Рекомендации для оптимального заживления.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [
                ("Какие образования можно удалить?", "Только доброкачественные образования кожи — бородавки, фибромы, небольшие элементы — и всегда после оценки. При любых сомнениях направляем на медицинское обследование до вмешательства."),
                ("Останется ли след или рубец?", "Стремимся к наилучшему заживлению; при правильном уходе след обычно минимальный, хотя результат зависит от образования и кожи."),
                ("Это больно?", "Процедура комфортная; в зависимости от образования возможна местная анестезия. Расскажем на консультации."),
                ("Сколько нужно сеансов?", "Многие образования удаляются за один сеанс; другие требуют контроля или дополнительного сеанса. Определяем при осмотре."),
                ("Сколько это стоит?", "Цена зависит от типа и числа образований, поэтому называем её после осмотра в нашем центре в Барселоне."),
            ],
        },
        "en": {
            "name": "Skin lesion removal",
            "tag": "Precise removal of benign skin lesions",
            "intro": [
                "We remove benign skin lesions with laser — such as warts, fibromas or small lesions — precisely and with good healing.",
                "Every lesion is assessed beforehand; where appropriate, it is referred for medical review before any procedure.",
            ],
            "benefits": ["Precise lesion removal", "Good healing", "Prior medical assessment", "Comfortable procedure"],
            "steps": [("Assessment", "We examine the lesion and decide the approach."), ("Laser procedure", "We remove the lesion with precision."), ("Care", "Aftercare guidance for optimal healing.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [
                ("Which lesions can be treated?", "Only benign skin lesions — such as warts, fibromas or small lesions — and always after an assessment. If there is any doubt about the lesion, it is referred for medical review before any procedure."),
                ("Will it leave a mark or scar?", "We aim for the best possible healing; with proper care the mark is usually minimal, though the result varies with the lesion and skin."),
                ("Is it painful?", "It is a comfortable procedure; local anaesthesia may be used depending on the lesion. We explain this at the assessment."),
                ("How many sessions do I need?", "Many lesions are removed in a single session; others need review or an extra session. We define this when assessing the lesion."),
                ("How much does it cost?", "The price depends on the type and number of lesions, so we give it after assessing them at our Barcelona clinic."),
            ],
        },
    },
    {
        "slug": "smas-lifting",
        "img": "/assets/svc-smas-lifting.jpg",
        "img2": "/assets/svc2-smas-lifting.jpg",
        "external": "https://smaslifting.es/",
        "es": {
            "name": "SMAS Lifting",
            "tag": "Lifting facial no invasivo con láser Fotona",
            "intro": [
                "El SMAS Lifting es un procedimiento moderno que reafirma la piel y ayuda a preservar su juventud, con tecnología láser Fotona que actúa sobre las capas profundas de la piel.",
                "Estimula la producción de colágeno para mejorar la firmeza y reducir las arrugas, sin cirugía, de forma cómoda y con un efecto duradero.",
            ],
            "benefits": ["Reafirma la piel del rostro", "Reduce las arrugas", "Efecto lifting sin cirugía", "Resultados duraderos y naturales"],
            "steps": [("Valoración", "Estudiamos tu piel y tus objetivos."), ("Sesiones láser", "El láser Fotona actúa en profundidad estimulando el colágeno."), ("Resultado", "La firmeza mejora de forma progresiva.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("¿Es doloroso?", "Es un tratamiento cómodo, sin necesidad de anestesia."), ("¿Cuántas sesiones necesito?", "Depende de tu piel y objetivos; lo definimos en la valoración.")],
        },
        "ca": {
            "name": "SMAS Lifting",
            "tag": "Lifting facial no invasiu amb làser Fotona",
            "intro": [
                "El SMAS Lifting és un procediment modern que reafirma la pell i ajuda a preservar-ne la joventut, amb tecnologia làser Fotona que actua sobre les capes profundes de la pell.",
                "Estimula la producció de col·lagen per millorar la fermesa i reduir les arrugues, sense cirurgia, de manera còmoda i amb un efecte durador.",
            ],
            "benefits": ["Reafirma la pell del rostre", "Redueix les arrugues", "Efecte lifting sense cirurgia", "Resultats duradors i naturals"],
            "steps": [("Valoració", "Estudiem la teva pell i els teus objectius."), ("Sessions làser", "El làser Fotona actua en profunditat estimulant el col·lagen."), ("Resultat", "La fermesa millora de manera progressiva.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("És dolorós?", "És un tractament còmode, sense necessitat d'anestèsia."), ("Quantes sessions necessito?", "Depèn de la teva pell i objectius; ho definim a la valoració.")],
        },
        "ru": {
            "name": "SMAS-лифтинг",
            "tag": "Неинвазивный лифтинг лица лазером Fotona",
            "intro": [
                "SMAS-лифтинг — современная процедура, которая уплотняет кожу и помогает сохранить молодость: лазер Fotona воздействует на глубокие слои кожи.",
                "Стимулирует выработку коллагена, повышая упругость и уменьшая морщины, без хирургии, комфортно и с длительным эффектом.",
            ],
            "benefits": ["Уплотняет кожу лица", "Уменьшает морщины", "Эффект лифтинга без хирургии", "Долгий и естественный результат"],
            "steps": [("Консультация", "Изучаем кожу и ваши цели."), ("Сеансы лазера", "Fotona работает в глубине, стимулируя коллаген."), ("Результат", "Упругость нарастает постепенно.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Это больно?", "Процедура комфортная, анестезия не нужна."), ("Сколько нужно сеансов?", "Зависит от кожи и целей; определим на консультации.")],
        },
        "en": {
            "name": "SMAS Lifting",
            "tag": "Non-invasive facial lifting with Fotona laser",
            "intro": [
                "SMAS Lifting is a modern procedure that firms the skin and helps preserve its youth, using Fotona laser technology that acts on the deep layers of the skin.",
                "It stimulates collagen production to improve firmness and reduce wrinkles, without surgery, comfortably and with a long-lasting effect.",
            ],
            "benefits": ["Firms the facial skin", "Reduces wrinkles", "Lifting effect without surgery", "Durable, natural results"],
            "steps": [("Assessment", "We study your skin and goals."), ("Laser sessions", "The Fotona laser works deep, stimulating collagen."), ("Result", "Firmness improves progressively.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Is it painful?", "It's a comfortable treatment, no anaesthesia needed."), ("How many sessions do I need?", "It depends on your skin and goals; we define it at the assessment.")],
        },
    },
    {
        "slug": "fotona-4glow",
        "img": "/assets/clinic-facial.jpg",
        "img2": "/assets/svc2-rejuvenecimiento-cutaneo.jpg",
        "external": "https://fotona4glow.es/",
        "badge": {"es": "Exclusivo", "ca": "Exclusiu", "ru": "Эксклюзив", "en": "Exclusive"},
        "es": {
            "name": "Fotona 4Glow",
            "tag": "Rejuvenecimiento facial 4 en 1, sin agujas ni cirugía",
            "intro": [
                "Fotona 4Glow es un tratamiento de rejuvenecimiento facial que combina de forma sinérgica las dos longitudes de onda del láser Fotona (Er:YAG y Nd:YAG) en cuatro modos, tratando varias capas de la piel en una sola sesión.",
                "Es un protocolo no invasivo, sin tiempo de recuperación, que mejora la firmeza, el tono, la textura y la luminosidad a la vez.",
            ],
            "benefits": ["Sin agujas ni cirugía", "Sin tiempo de recuperación", "Estimula el colágeno", "Firmeza, tono, textura y luminosidad"],
            "steps": [("SMOOTH", "Calentamiento profundo para efecto lifting."), ("FRAC3 · PIANO", "Trabaja pigmentación, líneas finas y dermis."), ("SupErficial", "Peeling ligero para un brillo final.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("¿Duele?", "Es un tratamiento cómodo, descrito como un calor agradable."), ("¿Necesito recuperación?", "No, puedes retomar tu rutina el mismo día.")],
        },
        "ca": {
            "name": "Fotona 4Glow",
            "tag": "Rejoveniment facial 4 en 1, sense agulles ni cirurgia",
            "intro": [
                "Fotona 4Glow és un tractament de rejoveniment facial que combina de manera sinèrgica les dues longituds d'ona del làser Fotona (Er:YAG i Nd:YAG) en quatre modes, tractant diverses capes de la pell en una sola sessió.",
                "És un protocol no invasiu, sense temps de baixa, que millora la fermesa, el to, la textura i la lluminositat alhora.",
            ],
            "benefits": ["Sense agulles ni cirurgia", "Sense temps de baixa", "Estimula el col·lagen", "Fermesa, to, textura i lluminositat"],
            "steps": [("SMOOTH", "Escalfament profund per a efecte lifting."), ("FRAC3 · PIANO", "Treballa pigmentació, línies fines i dermis."), ("SupErficial", "Peeling lleuger per a una lluïssor final.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Fa mal?", "És un tractament còmode, descrit com una calor agradable."), ("Necessito recuperació?", "No, pots reprendre la teva rutina el mateix dia.")],
        },
        "ru": {
            "name": "Fotona 4Glow",
            "tag": "Омоложение лица 4-в-1, без игл и хирургии",
            "intro": [
                "Fotona 4Glow — процедура омоложения лица, синергично сочетающая две длины волны лазера Fotona (Er:YAG и Nd:YAG) в четырёх режимах, прорабатывая несколько слоёв кожи за один сеанс.",
                "Это неинвазивный протокол без периода восстановления, который одновременно улучшает упругость, тон, текстуру и сияние.",
            ],
            "benefits": ["Без игл и хирургии", "Без периода восстановления", "Стимулирует коллаген", "Упругость, тон, текстура и сияние"],
            "steps": [("SMOOTH", "Глубокий прогрев для эффекта лифтинга."), ("FRAC3 · PIANO", "Работа с пигментом, мелкими линиями и дермой."), ("SupErficial", "Лёгкий пилинг для финального сияния.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Это больно?", "Комфортно, ощущается как приятное тепло."), ("Нужно восстановление?", "Нет, можно вернуться к делам в тот же день.")],
        },
        "en": {
            "name": "Fotona 4Glow",
            "tag": "4-in-1 facial rejuvenation, no needles or surgery",
            "intro": [
                "Fotona 4Glow is a facial rejuvenation treatment that synergistically combines the two Fotona laser wavelengths (Er:YAG and Nd:YAG) in four modes, treating several layers of the skin in a single session.",
                "It is a non-invasive protocol with no downtime that improves firmness, tone, texture and radiance at once.",
            ],
            "benefits": ["No needles or surgery", "No downtime", "Stimulates collagen", "Firmness, tone, texture and radiance"],
            "steps": [("SMOOTH", "Deep heating for a lifting effect."), ("FRAC3 · PIANO", "Works on pigmentation, fine lines and dermis."), ("SupErficial", "A light peel for a final glow.")],
            "tech": ["Er:YAG", "Nd:YAG"],
            "faq": [("Does it hurt?", "It's comfortable, described as a pleasant warmth."), ("Do I need recovery time?", "No, you can resume your routine the same day.")],
        },
    },
    {
        "slug": "control-de-peso",
        "group": "wellness",
        "external": "https://adelgazarnatural.es/",
        "es": {"name": "Control de peso", "tag": "Adelgazar con seguimiento médico"},
        "ca": {"name": "Control de pes", "tag": "Aprimar amb seguiment mèdic"},
        "ru": {"name": "Контроль веса", "tag": "Похудение под контролем врача"},
        "en": {"name": "Weight control", "tag": "Weight loss with medical supervision"},
    },
    {
        "slug": "salud-de-la-mujer",
        "group": "wellness",
        "external": "https://adelgazarnatural.es/salud-mujer.html",
        "es": {"name": "Salud de la mujer", "tag": "Equilibrio hormonal y bienestar"},
        "ca": {"name": "Salut de la dona", "tag": "Equilibri hormonal i benestar"},
        "ru": {"name": "Женское здоровье", "tag": "Гормональный баланс и самочувствие"},
        "en": {"name": "Women's health", "tag": "Hormonal balance and wellbeing"},
    },
    {
        "slug": "salud-del-hombre",
        "group": "wellness",
        "external": "https://adelgazarnatural.es/salud-hombre.html",
        "es": {"name": "Salud del hombre", "tag": "Equilibrio hormonal y energía"},
        "ca": {"name": "Salut de l'home", "tag": "Equilibri hormonal i energia"},
        "ru": {"name": "Мужское здоровье", "tag": "Гормональный баланс и энергия"},
        "en": {"name": "Men's health", "tag": "Hormonal balance and energy"},
    },
]
